### ISSUE TITLE
Add information on pageobject approach 

### ISSUE THREAD

**Issue by johndharrison** [ropensci/RSelenium#10]
Look into pageobject approach to testing and relate it to R and Shiny.

**Comment by jstockwin** [comment]
@johndharrison Did this ever happen? Is there existing functionality for pageobjects (POs) or is this something that needs manually implementing? 

I've used POs in both NodeJS and Python and am in the process of implementing some tests around an RShiny app. I've been thinking that the PO stuff would fit really nicely into this, and was intending on just doing some kind of manual implementation. Very keen to hear ideas/be pointed at existing code if this is something you've done already though? Thanks!
