### ISSUE TITLE
Explicit and Fluent Wait

### ISSUE THREAD

**Issue by msaidf** [ropensci/RSelenium#100]
It would be very useful if this package has command for Explicit and Fluent Wait method, besides the Implicit Wait method. Some element takes long time to load, so it is not efficient to set implicit wait time this long since it will affect all elements. Using explicit and fluent wait method, I can specify different time out for each element and continue once the condition is already met.

**Comment by grayskripko** [comment]
I wrote for myself waitFor function that waits for a specified thing. The thing can be an element, a list of element, a boolean expression or a function. The source can be webElement too. You can specify several targets as vector and the function will exit with the first met condition

```
waitFor <- function(target, source=driver, timeout=10) {
  nChecks <- 2 * timeout  # repeats a check twice per second
  oneWaitDur <- timeout / nChecks

  targetFun <- if (is.function(target)) target else 
    # getEls is my function for getting elements by query
    if (is.character(target)) function() sapply(target, function(x) getEls(source, x)) else
      if (is.call(target)) function() eval(target) else
        stop(sprintf('Not implemented for target class [%s]', class(target)))

  for (i in 1:nChecks) {
    res <- suppressWarnings(targetFun())
    if (is.list(res)) {
      if (length(target) == 1) {
        if (length(res)) {
          return(invisible(if (length(res) > 1) res else res[[1]]))
        }
      } else {
        if (length(Filter(length, res)) == 1) {
          res <- Filter(length, res)[[1]]
          return(invisible(if (length(res) > 1) res else res[[1]]))
        }
      }
    } else if (is.logical(res) && res) {
      return(res)
    }
    Sys.sleep(oneWaitDur)
  }
  driver$screenshot(T)
  stop('Could not wait')
}

# el <- waitFor('#someElId')  # waits and returns the waited element
# waitFor('#someElId', source=el, timeout=5)
```

**Comment by johndharrison** [comment]
@grayskripko thanks for sharing this code. I will look over it and see if it is something that can be incorporated into the remoteDriver class.
