### ISSUE TITLE
Is the instructions in "RSelenium basics" outdated?

### ISSUE THREAD

**Issue by yutannihilation** [ropensci/RSelenium#101]
Hi, thanks for this great package.

As NEWS says, `startServer` and `checkForServer` were deprecated in RSelenium 1.4.4. But the vignette still refers them in the section ["How do I get the Selenium Server stand-alone binary?"](https://cran.r-project.org/web/packages/RSelenium/vignettes/RSelenium-basics.html#how-do-i-get-the-selenium-server-stand-alone-binary) and ["How do I run the Selenium Server?"](https://cran.r-project.org/web/packages/RSelenium/vignettes/RSelenium-basics.html#how-do-i-run-the-selenium-server).

Should I rely on these functions for now or not?

**Comment by johndharrison** [comment]
Hi @yutannihilation the basics is outdated. The checkForServer and startServer functions are deprecated as they were unreliable cross-platform. ATM I am unaware of a reliable way to manage a process cross platform via R. The functions remain as they are and have been moved to the example/serverUtils folder. 

```
file.path(find.package(\"RSelenium\"), \"example/serverUtils\")
```

The recommended `RSelenium` way to run a Selenium Server with a browser is via Docker. There is a vignette detailing how this can be done http://rpubs.com/johndharrison/RSelenium-Docker . The Docker image should remain unchanged pulling a compatible browser/driver combination and create less compatibility issues on the user end.

**Comment by yutannihilation** [comment]
@johndharrison Thanks for your quick response! Sure, I will use Docker 👍. (Cross platform is really a tough job... I greatly appreciate your effort.)

**Comment by johndharrison** [comment]
@yutannihilation the Basics vignette has been updated and a new version should hopefully be pushed to CRAN shortly.

http://rpubs.com/johndharrison/RSelenium-Basics

**Comment by yutannihilation** [comment]
@johndharrison Wow, seems nice! Thanks!
