### ISSUE TITLE
Feature/Question: cross container communication: container A (with R and Rselenium) sending commands to drive container B (Firefox/selenium) 

### ISSUE THREAD

**Issue by mikejacktzen** [ropensci/RSelenium#102]
# Question:
Is it possible to run selenium (and other R code) in the os environment of container A
but depending on the Firefox/selenium image housed in container B?

I'm not an expert on docker, but it looks like cross container communication is possible:
http://rpubs.com/johndharrison/RSelenium-Docker

# I'm thinking it's all about matching the (ip / ports) of the: Host machine + container A + container B

## docker container A with
* R 
* Rselenium
* other R packages

## docker container B with
the standalone docker image Firefox/selenium
http://rpubs.com/johndharrison/RSelenium-Docker

## Docker commands to run container A 
```
 docker run -ti -p 4443:4442 rselphan
```

## Docker command to run container B
```
 docker run -d -p 4445:4444 selenium/standalone-firefox:2.53.0
```

## R code executed inside container A
```
remoteServerAddr_choose = "what should go here"
port_choose = "what should go here"

remDr <- remoteDriver(
  remoteServerAddr = remoteServerAddr_choose,
  port = port_choose)  
remDr$open(silent = TRUE)
```

### Container A with R and Rselenium

```
    "NetworkSettings": {
        "Bridge": "docker0",
Gateway= 123.45.67.8 (fake)
IPAddress": "876.54.3.210" (fake)
        "Ports": {
            "4442/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "4443"
                }
            ]
        }

```

### Container B with Selenium/Firefox

```
    "NetworkSettings": {
        "Bridge": "docker0",

Gateway= 123.45.67.8 (fake) (Note: same gateway ip as container A)
IPAddress": "876.54.3.211" (fake) (Note: different IPAddress than container A)

        "Ports": {
            "4444/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "4445"
                }
            ]
        }
```

**Comment by johndharrison** [comment]
Hi Mike,

You should just be able to name the Selenium container:

```
 docker run -d -p 4445:4444 --name myselcontainer selenium/standalone-firefox:2.53.0
```

the old way would be to then link it in the other container:

```
docker run -ti -p 4443:4442 --link=myselcontainer rselphan
```

In container A you should be now able to access the Selenium Server using for example:
```
remDr <- remoteDriver(remoteServerAddr = myselcontainer, port = 4444L)
```

**Comment by mikejacktzen** [comment]
Wow, @johndharrison  thanks for the quick answer. I tried it, made a slight modification, and it works.

# note the name:alias syntax of myselcontainer:myselcontainer
(this syntax seems to be tied to the docker version running on the global host)

 docker run -d -p 4445:4444 --name myselcontainer:myselcontainer selenium/standalone-firefox:2.53.0

docker run -ti -p 4443:4442 --link=myselcontainer rselphan

# note the quotes around 'myselcontainer '
remDr <- remoteDriver(remoteServerAddr = 'myselcontainer', port = 4444L)

remDr$open(silent = TRUE)
remDr$navigate("http://www.google.com/ncr")
remDr$getTitle()

**Comment by johndharrison** [comment]
Ha top stuff containers are pretty awesome (when they work lol)

**Comment by johndharrison** [comment]
@mikejacktzen 

As mentioned the old way this was done was via linking as above. Now Docker advises to use 
docker compose. 

As an example we create a new folder:
```
> mkdir rdocker
> cd rdocker
```

In this new folder we add a `docker-compose.yml` file. In this file we define the services we want:

```
version: '2'
services:
  ropensci: 
    image: rocker/ropensci
    ports:
      - "8788:8787"
    links:
      - selenium:selenium
  selenium:
    image: selenium/standalone-firefox:2.53.0
    ports:
      - "4445:4444"
```

Then we run our yaml file with docker compose:

```
> docker-compose up
```

Rstudio server should now be accessible onthe host on port 8788. We can log in with user = rstudio, 
pass = rstudio.  The following code can then be run

```
library(RSelenium)
remDr <- remoteDriver(remoteServerAddr = "selenium", port = 4444L)
remDr$open()
remDr$navigate("http://www.r-project.org")
remDr$screenshot(display = TRUE)
```

**Comment by Tazovsky** [comment]
So I run code:

 ```
docker run -d -p 4445:4444 --name myselcontainer selenium/standalone-firefox:2.53.0 # container B
docker run -ti -p 4443:4442 --link=myselcontainer rselphan # container A
```
and this works in container A:
```
remDr <- remoteDriver(remoteServerAddr = "myselcontainer", port = 4444L, browser = "chrome")
remDr$open()
remDr$navigate("http://www.google.com/ncr")
remDr$getTitle()
[[1]]
[1] "Google"
```

but my intention is to test Shiny app which is in container A by running Rselenium tests. Any suggestions how to do it well?

**Comment by johndharrison** [comment]
This setup works for me. Create two containers A + B. A runs shiny apps. B runs a selenium server.
Now on your Host machine you can run an R session and access the selenium server on port 4445.
The selenium server container is linked to the shiny container and can access it on http://shiny:3838

```
# container to run shiny
# docker run -d -p 3838:3838 --name myselcontainer rocker/shiny 
# link container to run selenium to shiny container
# docker run -d -p 4445:4444 --name selenium --link shiny selenium/standalone-chrome 


remDr <- remoteDriver(remoteServerAddr = "localhost" 
                      , port = 4445L
                      , browserName = "chrome")

remDr$open()

remDr$navigate("http://www.google.com/ncr")
> remDr$getTitle()
[[1]]
[1] "Google"

remDr$screenshot(display = TRUE)
remDr$navigate("http://shiny:3838")
> remDr$getTitle()
[[1]]
[1] "Welcome to Shiny Server!"

remDr$screenshot(display = TRUE)
```

![tmpscreenshot](https://user-images.githubusercontent.com/2418258/29712249-df97466c-8990-11e7-84b8-515a314bd1d0.png)
