### ISSUE TITLE
chrome hangs on $navigate

### ISSUE THREAD

**Issue by glennmschultz** [ropensci/RSelenium#104]
Everything seem to work until I $navigate - Here is the code I am using
require(RSelenium)
 chromeprofile <- "Users/glennschultz/Library/Application Support/Google/Chrome/"
 PoolTalk <- "https://mbsdisclosure.fanniemae.com/PoolTalk/index.html"
 
 RSelenium::checkForServer(update = TRUE)
 RSelenium::startServer()
 
 cprof <- RSelenium::getChromeProfile(dataDir = chromeprofile, profileDir = "Default")
 remDr <- remoteDriver(remoteServerAddr = "localhost" 
                       , port = 4444
                       , browserName = "chrome"
                       ,extraCapabilities = cprof)
 remDr$open()
 remDr$getStatus()
 remDr$value
 
 remDr$navigate("https://mbsdisclosure.fanniemae.com/PoolTalk/index.html")

Here is error message
remDr$navigate("https://mbsdisclosure.fanniemae.com/PoolTalk/index.html")
Error: 	 Summary: UnknownError
 	 Detail: An unknown server-side error occurred while processing the command.
 	 class: org.openqa.selenium.WebDriverException
> Here is remDr$value
remDr$value
$build
$build$version
[1] "3.0.1"

$build$revision
[1] "1969d75"

$build$time
[1] "2016-10-18 09:48:19 -0700"

$os
$os$name
[1] "Mac OS X"

$os$arch
[1] "x86_64"

$os$version
[1] "10.12.1"

$java
$java$version
[1] "1.8.0_101"

**Comment by glennmschultz** [comment]
I have loaded Mac Docker and have a virtual machine for chrome running.  I believe Mac Docker uses localhost so now I have the following with remapping of ports


remDr <- RSelenium::remoteDriver(remoteServerAddr = "localhost"
                                 ,port = 4455L
                                 ,browserName = "chrome"
                                 ,extraCapabilities = cprof)
Chrome failed to start I have chrome.exe in ~glennschultz
and in the Application Support  for chrome.  Any idea where I need to chrome.exe?

remDr$open()
[1] "Connecting to remote server"
$webdriver.remote.sessionid
[1] "1bd991da-4154-4867-bfa5-d49e61e945b8"

$locationContextEnabled
[1] TRUE

$webStorageEnabled
[1] TRUE

$takesScreenshot
[1] TRUE

$javascriptEnabled
[1] TRUE

$message
[1] "unknown error: Chrome failed to start: crashed\n  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.12.1 x86_64)"

$hasTouchScreen
[1] TRUE

$platform
[1] "ANY"

$cssSelectorsEnabled
[1] TRUE

$id
[1] "1bd991da-4154-4867-bfa5-d49e61e945b8"

>

**Comment by johndharrison** [comment]
Are you running "Docker for Mac" or "Docker Toolbox"?

**Comment by glennmschultz** [comment]
Docker for Mac

**Comment by johndharrison** [comment]
Can you give the docker run command you used?

**Comment by glennmschultz** [comment]
Basically, I copied from your vignette
docker run -d -p 4445:4444 selenium/standalone-chrome

docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                    NAMES
4416d0b54d01        selenium/standalone-chrome   "/opt/bin/entry_point"   15 minutes ago      Up 15 minutes       0.0.0.0:4445->4444/tcp   berserk_thompson

**Comment by glennmschultz** [comment]
> remDr$value
$build
$build$version
[1] "3.0.1"

$build$revision
[1] "1969d75"

$build$time
[1] "2016-10-18 09:48:19 -0700"


$os
$os$name
[1] "Mac OS X"

$os$arch
[1] "x86_64"

$os$version
[1] "10.12.1"


$java
$java$version
[1] "1.8.0_101"

**Comment by johndharrison** [comment]
The port would be:

remDr <- RSelenium::remoteDriver(remoteServerAddr = "localhost"
,port = 4445L
,browserName = "chrome"
,extraCapabilities = cprof)

rather than 4455L. Also your "cprof" refers to a directory on the host. The container will not be able to access this.

**Comment by glennmschultz** [comment]
oh God, now I really feel like and idiot.  I have been working on the docker thing all night and totally missed that

**Comment by glennmschultz** [comment]
remDr$open()
[1] "Connecting to remote server"
$webdriver.remote.sessionid
[1] "22972bfe-27b7-4182-a735-aa14218fd6fe"

$locationContextEnabled
[1] TRUE

$webStorageEnabled
[1] TRUE

$takesScreenshot
[1] TRUE

$javascriptEnabled
[1] TRUE

$message
[1] "unknown error: cannot create default profile directory\n  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 4.4.27-moby x86_64)"

$hasTouchScreen
[1] TRUE

$platform
[1] "ANY"

$cssSelectorsEnabled
[1] TRUE

$id
[1] "22972bfe-27b7-4182-a735-aa14218fd6fe"

>

**Comment by glennmschultz** [comment]
a guy on SO says cannot use quotes so I removed cprof
remDr <- RSelenium::remoteDriver(remoteServerAddr = "localhost"
                                 ,port = 4445L
                                 ,browserName = "chrome")
                                 #,extraCapabilities = cprof)

The chrome browser does not appear but it looks like it is working.  why doesn't the browser pop-up like before?


remDr$open()
[1] "Connecting to remote server"
$applicationCacheEnabled
[1] FALSE

$rotatable
[1] FALSE

$mobileEmulationEnabled
[1] FALSE

$networkConnectionEnabled
[1] FALSE

$chrome
$chrome$chromedriverVersion
[1] "2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e)"

$chrome$userDataDir
[1] "/tmp/.org.chromium.Chromium.G1vrqw"


$takesHeapSnapshot
[1] TRUE

$pageLoadStrategy
[1] "normal"

$databaseEnabled
[1] FALSE

$handlesAlerts
[1] TRUE

$hasTouchScreen
[1] TRUE

$version
[1] "54.0.2840.71"

$platform
[1] "LINUX"

$browserConnectionEnabled
[1] FALSE

$nativeEvents
[1] TRUE

$acceptSslCerts
[1] TRUE

$webdriver.remote.sessionid
[1] "c1d82857-ee04-4012-934f-6398d7d782b5"

$locationContextEnabled
[1] TRUE

$webStorageEnabled
[1] TRUE

$browserName
[1] "chrome"

$takesScreenshot
[1] TRUE

$javascriptEnabled
[1] TRUE

$cssSelectorsEnabled
[1] TRUE

$id
[1] "c1d82857-ee04-4012-934f-6398d7d782b5"

**Comment by johndharrison** [comment]
Yeah thats expected as noted above your cprof refers to a directory on the host. You will need to add a slight adjustment to your docker run command. You would need to map a directory on the host to a directory on the container. cprof would refer to the container location. In the host you would move your chrome profile to the hosts mapped directory.

**Comment by johndharrison** [comment]
> The chrome browser does not appear but it looks like it is working. why doesn't the browser pop-up like before?

The chrome browser is running headlessly. To have a chrome browser that you can see you would need to use the "debug" image:

```
docker run -d -p 4445:4444 -p 5901:5900 selenium/standalone-chrome-debug
```

You can then view the container browser using a vnc viewer. In MAC this is straightforward:

Goto safari and type:

vnc://localhost:5901

This will bring up a VNC viewer. If the VNC viewer asks for a password it is "secret" as noted in the Docker vignette.

**Comment by glennmschultz** [comment]
I thought it was running headless.  I need to pass username/password/checkbox.  I was planning on writing my code with the browser then changing to headless.  I read you vignette the 3 things a browser can do.  Maybe I will just try headless.  Will let you know.  Thanks for you time and help

**Comment by glennmschultz** [comment]
Followed the instructions above and used the below code.

"Connecting to remote server"
Undefined error in RCurl call.
Error in queryRD(paste0(serverURL, "/session"), "POST", qdata = toJSON(serverOpts)) : 
  
The same code without the -debug connects to the server

require(RSelenium)
PoolTalk <- "https://mbsdisclosure.fanniemae.com/PoolTalk/index.html"

#RSelenium::checkForServer(update = TRUE)
remDr <- RSelenium::remoteDriver(remoteServerAddr = "localhost"
                                 ,port = 4445L
                                 ,browserName = "chrome")

# need to create some logic around system checking for the VM is it does
# not exist then run a system command to start the machine
#system2("docker run -d -p 4445:4444 selenium/standalone-chrome", wait = TRUE)

remDr$open()
remDr$navigate("https://mbsdisclosure.fanniemae.com/PoolTalk/index.html")

LoginUserName <- remDr$findElement(using = 'id', "loginUsername")
LoginPassWord <- remDr$findElement(using = 'id', "loginPassword")
TermsConditions <- remDr$findElement(using = 'id', "isTermsAndConditionsSelected")
LoginBtn <- remDr$findElement(using = 'id', 'loginBtn')

LoginUserName$sendKeysToElement(list('glennmschultz@me.com'))
LoginPassWord$sendKeysToElement(list('Alaska0718@'))
TermsConditions$sendKeysToElement(key = 'space')
