### ISSUE TITLE
Disabling images - Rselenium chromedriver

### ISSUE THREAD

**Issue by SNaveenMathew** [ropensci/RSelenium#105]
Python has the option to disable images:
http://stackoverflow.com/questions/28070315/python-disable-images-in-selenium-google-chromedriver

I could not find an equivalent method in R to turn off images. I tried changing the content settings to disable images and restarted the browser - did not work.

I also tried to create a profile and send it as parameter, but it did not work:
RSelenium::makeFirefoxProfile(opts = list(images=2))
Error in file(tmpfile, "rb") : cannot open the connection

**Comment by johndharrison** [comment]
You can set this preference as follows:

```
library(RSelenium)
prefs = list("profile.managed_default_content_settings.images" = 2L)
cprof <- list(chromeOptions = list(prefs = prefs))
remDr <- remoteDriver(browserName = 'chrome', extraCapabilities = cprof,
                      port = 4567L) # change port as suits
remDr$open()
remDr$navigate("http://www.google.com/ncr")
```

**Comment by SNaveenMathew** [comment]
Thanks @johndharrison for the working solution.
