### ISSUE TITLE
R Session Hangs when using For Loop to Scrape

### ISSUE THREAD

**Issue by abasees** [ropensci/RSelenium#106]
When running the below code I find that the R session Hangs. I'm using PhantomJS version 2.1.1 (I've tried with 1.9.2 but it could not locate the element it seems) and the latest RSelenium. This seems to be similar to the issue mentioned https://github.com/ropensci/RSelenium/issues/95 by @huashan. I'm running this on windows 7 64 bit. 

I've done some research into this, and I'm not sure if it is related to this issue located here:
https://github.com/detro/ghostdriver/issues/397

Maybe not related, but I noticed that the sys.sleep time changed how far the for loop got into the scraping process, for example the code below did it till i = 15, but if I use sys.sleep(1) it will go to i = 8 or 9 roughly.

If there is anything else I can provide, please let me know!

```
# NOTE: xxx_file_xxx is just a list of characters to submit to a search bar and URL contains the site URL.

require(RSelenium)
pJS <- phantom()
Sys.sleep(5)
remDr <- remoteDriver(browserName = 'phantomjs')
remDr$open()

remDr$navigate(URL)

for (i in 1:n){
  rand = sample(20:100,1)/100
  Sys.sleep(1*rand)
  
  pause_when = floor(cumsum(rep(0.25*n,4)))
  if (i %in% pause_when){
    Sys.sleep(sleep_time)
  }
  
  webElem = remDr$findElement(using = 'xpath', value = '//*[(@id = "address")]')
  webElem$sendKeysToElement(list(xxx_file_xxx[i], "\uE007"))

  psScript = paste0("var page = this; var fs = require(\"fs\"); fs.write(\"",name,i,".txt\", page.content, 'w');")
  result = remDr$phantomExecute(psScript)
}

remDr$close
pJS$stop()
```

**Comment by johndharrison** [comment]
This seems to be an issue with `RCurl` and how it interacts with `phantom`:

```
pJS <- phantom()
Sys.sleep(5)
for (i in 1:100){
  cat("in", i, "\n")
  RCurl::getURL("http://localhost:4444/wd/hub/sessions",
               .opts = list(timeout = 10))
}
pJS$stop()
```

We dont see this issue for example:

```
pJS <- phantom()
Sys.sleep(5)
for (i in 1:100){
  cat("in", i, "\n")
  readLines("http://localhost:4444/wd/hub/sessions")
}
pJS$stop()
```

**Comment by johndharrison** [comment]
@abasees When you get a chance can you test this inc_httr branch:
```
devtools::install_github("ropensci/RSelenium@inc_httr")
```

It should address the issue you observed.

**Comment by abasees** [comment]
@johndharrison I'll try to test this today hopefully, but first could you clarify what to do, I'm unfamiliar with the code given

**Comment by johndharrison** [comment]
@abasees you can use the `devtools` package to install the dev branch from github:

```
install.packages("devtools")
devtools::install_github("ropensci/RSelenium@inc_httr")
```

**Comment by abasees** [comment]
Hi John, I've just tested it now and it seems so far to be working much further than previous, I'll let you know if it hangs at anytime in the for loop.

**Comment by johndharrison** [comment]
Closing this assumming #107 addresses the issue. @abasees if you encounter issues related to this please update.
