### ISSUE TITLE
How to use Selenium Select Class

### ISSUE THREAD

**Issue by bedantaguru** [ropensci/RSelenium#108]
My intention is simple I want to use Select class as depicted in 
https://stackoverflow.com/questions/16768318/how-can-i-get-all-elements-from-drop-down-list

Also as is Pyhton you can do select = Select(driver.find_element_by_name('name'))

I want same functionality in RSelenium. I was going through the code and felt like something I have to do with queryRD but I need a proper guidance. 

For reference 
```
remDr$navigate("http://nhb.gov.in/OnlineClient/MonthlyPriceAndArrivalReport.aspx")

elem<- list()

elem$year <- remDr$findElement(using = "id", value = "ctl00_ContentPlaceHolder1_ddlyear")
```

Now I want all the years in the field.

**Comment by bedantaguru** [comment]
`from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
#from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.support.ui import Select
 
firefoxCap = DesiredCapabilities.FIREFOX
#we need to explicitly specify to use Marionette
firefoxCap["marionette"] = True
#firefoxCap["binary"] = r'C:\Program Files (x86)\Mozilla Firefox\firefox.exe'
binary = FirefoxBinary(r'C:\Program Files (x86)\Mozilla Firefox\firefox.exe')

driver = webdriver.Firefox(capabilities = firefoxCap, firefox_binary = binary)

driver.get("http://nhb.gov.in/OnlineClient/MonthlyPriceAndArrivalReport.aspx")
#assert "Python" in driver.title
elem = driver.find_element_by_id("ctl00_ContentPlaceHolder1_ddlyear")
selopts = Select(elem)
selopts = selopts.options
#assert "No results found." not in driver.page_source
driver.close()`

**Comment by johndharrison** [comment]
@bedantaguru You can define a function to extract the information you may want:

```
selectTag = function(element){
    if(!inherits(element, "webElement")){
      stop("element should be a web element.")
    }
    if(!identical(element$getElementTagName()[[1]], "select")){
      stop("element does not appear to point to a select element in DOM.")
    }
    options <- element$findChildElements("css", "option")
    optiontext <- vapply(options, 
                         function(x)x$getElementText()[[1]], 
                         character(1)
    )
    optionvalues<- vapply(options, 
                          function(x)x$getElementAttribute("value")[[1]], 
                          character(1)
    )
    list(elements = options, text = optiontext, value = optionvalues)
}
```
for example

```
remDr$navigate("http://nhb.gov.in/OnlineClient/MonthlyPriceAndArrivalReport.aspx")
elem <- remDr$findElement(
  using = "id", 
  value = "ctl00_ContentPlaceHolder1_ddlyear"
)
mySelect <- selectTag(elem)

> mySelect$value
 [1] "2016" "2015" "2014" "2013" "2012" "2011" "2010" "2009" "2008" "2007" "2006"
[12] "2005" "2004" "2003" "2002" "2001" "2000"
> mySelect$text
 [1] "2016" "2015" "2014" "2013" "2012" "2011" "2010" "2009" "2008" "2007" "2006"
[12] "2005" "2004" "2003" "2002" "2001" "2000"
```

**Comment by bedantaguru** [comment]
wow that's great it's working like a charm.

**Comment by bedantaguru** [comment]
wow that's great it's working like a charm.

**Comment by johndharrison** [comment]
This has now been added as a method of the webDriver class and can be called as:

```
remDr$navigate("http://nhb.gov.in/OnlineClient/MonthlyPriceAndArrivalReport.aspx")
elem <- remDr$findElement(
  using = "id", 
  value = "ctl00_ContentPlaceHolder1_ddlyear"
)
options <- elem$selectTag()
```

**Comment by bedantaguru** [comment]
I could not find `selectTag`  in the current code is it in a separate branch. 
Apologies for my limited knowledge but how can I get that? _[by installing development version using devtools ?]_

**Comment by johndharrison** [comment]
v1.6.2 with fixes as above is on CRAN now thanks. The `selectTag` method is callable from any `webElement`
object.

**Comment by bedantaguru** [comment]
That's great, Really great, thanks a lot for your kind effort and time.
