### ISSUE TITLE
webElement$getElementAttribute returns the last attribute when it is absent

### ISSUE THREAD

**Issue by grayskripko** [ropensci/RSelenium#109]
![image](https://cloud.githubusercontent.com/assets/10427026/20794961/80f1549e-b7d7-11e6-8fa9-379a9bccdc5b.png)

**Comment by grayskripko** [comment]
did you need more details?
Is it a bug or I missed something? 
If it is a bug should I write a workaround or you can fix it quickly?

**Comment by johndharrison** [comment]
Can you try the most uptodate dev branch of RSelenium and see if the issue is still occurring.
devtools::install_github("ropensci/RSelenium@update_vig").

**Comment by grayskripko** [comment]
thank you. I see the problem is gone on the latest CRAN version.
Now I can detect a missing attribute by the first element name. It must be empty.
But this '0' value confuses me as a user. An attribute value can be presented and be equal zero.

![image](https://cloud.githubusercontent.com/assets/10427026/20800813/74fc672e-b7ef-11e6-9746-3028cb6af83f.png)

**Comment by grayskripko** [comment]
though, using suggested devtools::install_github("ropensci/RSelenium@update_vig") solves the problem

![image](https://cloud.githubusercontent.com/assets/10427026/20801176/a8441748-b7f0-11e6-810c-c9cfea869f43.png)

When are you going to publish it to CRAN?
I can not use such local version of RSelenium in my public project.

**Comment by johndharrison** [comment]
@grayskripko I will be issuing a new version to CRAN shortly. The currently dev branch has switched to httr from RCurl due to issues with RCurl hanging. I am looking to update the vignettes and then I will be pushing to CRAN.

**Comment by grayskripko** [comment]
thank you very much!
In this case, I'm going to use current dev version.

**Comment by johndharrison** [comment]
v1.6.2 with fixes as above is on CRAN now thanks.
