### ISSUE TITLE
Phantom JS version for R Shiny

### ISSUE THREAD

**Issue by jamesthesnake** [ropensci/RSelenium#111]
Since RSelenium is now apporved for Shiny, I use it to install phantom JS on the R sever , but it says the phantomjs version less than 1.9.1 is this true? and if so is it possible to update the version?
<img width="969" alt="screen shot 2016-12-08 at 1 19 15 pm" src="https://cloud.githubusercontent.com/assets/8227820/21021991/0304e1fa-bd49-11e6-957c-9d9a39bbefe7.png">

**Comment by johndharrison** [comment]
This looks like its an issue related to webshot
