### ISSUE TITLE
RSelenium Web Driver for FireFox Crashing

### ISSUE THREAD

**Issue by d84-n1nj4** [ropensci/RSelenium#112]
Hi, 

I recently had to upgrade to Firefox 50.0.2 and I lost all the functionality of my web-scraping code. I followed the advice of [http://stackoverflow.com/questions/39886377/a-error-occur-in-remotedriver-function-of-rselenium](url), but to no avail. Here is the following code:

```
`> selServ <- RSelenium::startServer(javaargs = c("-Dwebdriver.gecko.driver=\"C:/Gecko/geckodriver.exe\""))
Warning message:
startServer is deprecated.
Users in future can find the function in 
file.path(find.package("RSelenium"), "example/serverUtils").
The sourcing/starting of a Selenium Server is a users responsiblity. 
Options include manually starting a server see 
vignette("RSelenium-basics", package = "RSelenium")
and running a docker container see  
vignette("RSelenium-docker", package = "RSelenium") 
`
`remDr <- remoteDriver(extraCapabilities = list(marionette = TRUE))`
`> selServ <- startServer()
Warning message:
startServer is deprecated.
Users in future can find the function in 
file.path(find.package("RSelenium"), "example/serverUtils").
The sourcing/starting of a Selenium Server is a users responsiblity. 
Options include manually starting a server see 
vignette("RSelenium-basics", package = "RSelenium")
and running a docker container see  
vignette("RSelenium-docker", package = "RSelenium") `
`> remDr$open(silent=T)
```
Selenium message:Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:`

Any help on this would be greatly appreciated.

**Comment by johndharrison** [comment]
If firefox has updated you may need an updated geckodriver check https://github.com/mozilla/geckodriver/releases for the latest version

**Comment by d84-n1nj4** [comment]
I updated to the latest gecko driver "geckodriver-v0.11.1-win64.zip".

**Comment by d84-n1nj4** [comment]
Is there going to be an updated release of RSelenium, not the beta? If so, about how long would that be? I am having to convert my code to Python and find R much easier for html table parsing.

**Comment by johndharrison** [comment]
What version of Selenium server are you running. http://selenium-release.storage.googleapis.com/index.html
the most recent version is [selenium-server-standalone-3.0.1.jar](http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar)

**Comment by d84-n1nj4** [comment]
How do I check the version of selenium? I went into my RSelenium\bin folder and the jar file doesn't specify a date. It is just "selenium-server-standalone.jar".

**Comment by johndharrison** [comment]
`RSelenium::checkForServer(update = TRUE)` should download the most recent Selenium binary.

**Comment by d84-n1nj4** [comment]
I was able to remDr to work now, thank you for that. However, I am getting errors when I run my code now. The majority of the errors seems to come from this error: "package ‘httr’ was built under R version 3.3.2 ". Would this be related to working with a beta version?

**Comment by johndharrison** [comment]
Firefox and geckodriver are currently in a transition state

> Since Firefox version 48, Mozilla requires all add-ons to be signed. Until
recently, Firefox support in Selenium was exclusively provided by an add-on.
As this add-on is not currently signed, this solution does not work with the
latest Firefox releases. As an alternative, Mozilla are working on a WebDriver
specification compliant implementation named GeckoDriver. Please note that the specification is not complete, and that Selenium itself does not comply with
the specification at this time. This means that features previously available
through Selenium will not be available using GeckoDriver.

> Any issue logged here for Firefox 48 or later will be closed as a duplicate of
#2559. Our recommendation is to switch to GeckoDriver, or to continue testing
on Firefox 45 until GeckoDriver is a viable option for you. If you are
interested in helping us to sign the add-on to restore support for later
Firefox versions, please see the following comment for what's needed:
https://github.com/SeleniumHQ/selenium/issues/2942#issuecomment-259717567


Geckodriver is currently implementing the w3c webdriver spec which is incomplete at this point in time. 
If you want to test with firefox I would recommend using an older selenium server version with an older compatible version of firefox. The easiest way to do this is running a Docker container. There is a vignette on this http://rpubs.com/johndharrison/RSelenium-Docker
