### ISSUE TITLE
Element Clickable

### ISSUE THREAD

**Issue by msgoussi** [ropensci/RSelenium#115]
### Operating System
Windows 7
### Selenium Server version
rselenium version 1.6.1
### Browser version (firefox, chrome etc.)
Chrome
### Other driver version (chromedriver, geckodriver, iedriver, PhantomJS etc.)
ChromeDriver 2.27
### Steps to reproduce the behaviour

Dear Mr. John,
I have computers, I am not facing this problem with Windows 10 but I am facing it with windows 7.

One of the element is taking long time until the website is completely loading.
I would like to pause until the element is clickable. How to do this?

Error I get:
Selenium message:unknown error: Element <a href="" ng-click="getExcelfile()">...</a> is not clickable at point (593, 8). Other element would receive the click: <div class="blockUI blockOverlay" style="z-index: 1000; border: none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(237, 237, 237); opacity: 0.734109; cursor: default; position: fixed;"></div>
  (Session info: chrome=55.0.2883.87)
  (Driver info: chromedriver=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa30),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 55 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'IRI-310677-M93P', ip: '10.56.110.34', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.26.436362 (5476ec6bf7ccbada1734a0cdec7d570bb042aa30), userDataDir=C:\Users\310677\AppData\Local\Temp\scoped_dir9024_12375}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=55.0.2883.87, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 72eb296a7d9e0db802a36e0b351020e7

 Show Traceback
 
 Rerun with Debug
 Error: 	 Summary: UnknownError
 	 Detail: An unknown server-side error occurred while processing the command.
 	 class: org.openqa.selenium.WebDriverException
	 Further Details: run errorDetails method 

Code I am using
# Selenium driver
selenium.driver<-function(spath=NULL){
  # Remove files in directory
  file.remove(list.files(seleniumfolder,full.names=TRUE))
  if (is.null(spath)){spath<-seleniumfolder}
  extraCapabilities<-list(
    chromeOptions=list(
      prefs=list(
        download.default_directory=spath,
        download.directory_upgrade=TRUE,
        download.extensions_to_open="",
        download.prompt_for_download=FALSE)))
  # Check if Selenium Server stanalone binary is present
  RSelenium::checkForServer()
  # RSelenium::startServer(args=c("webdriver.ie.driver=C:/RSelenium/IEDriverServer.exe",log=FALSE,invisible=FALSE))
 selServ<-startServer(javaargs=c('-Dwebdriver.chrome.driver="C:/RSelenium/chromedriver.exe"'))
  return(remoteDriver(browserName="chrome",extraCapabilities=extraCapabilities))}

url<-"http://ppi.worldbank.org/explore/Report.aspx?mode=1"
syear<-as.numeric(format(Sys.time(),"%Y"))-1990+1
 usingpath<-c(# Aggregated Data Reports
                    "xpath","//*/input[@name='reporttype'][@value='2']",
                    # Investment Summaries
                    "xpath","//div[@class='advanced-report-selection']/div[1]/div[2]/select//option[@value='1']",
                    # Year 1990
                    "xpath",
                    paste0("//div[@class='advanced-report-selection']/div[2]/select[1]//option[",syear,"]"),
                    # Country
                    "xpath","//table[@class='select-block']/tbody/tr/td[2]/select//option[5]",
                    # Investment Year
                    "xpath","//table[@class='select-block']/tbody/tr/td[4]/select//option[4]",
                    # Primary Sector
                    "xpath","//table[@class='select-block']/tbody/tr/td[6]/select//option[3]",
                    # Sub Sector
                    "xpath","//table[@class='select-block']/tbody/tr/td[8]/select//option[8]",
                    # ICT Sector
                    "xpath","//div[@class='primary-sector']/div[3]/ul/li[1]/label/input",
                    # Transport Sector
                    "xpath","//div[@class='primary-sector']/div[4]/ul/li[1]/label/input",
                    # Water and sewerage Sector
                    "xpath","//div[@class='primary-sector']/div[5]/ul/li[1]/label/input",
                    # Country Tab
                    "link text","Choose Countries",
                    # List of Countries
                    "xpath","//li[@class='second']//label[.=' Use country list']",
                    "link text","Search",
                    "link text","Download to Excel")

  # Assign Browser
  mybrowser<-selenium.driver()
  # Main Window
  mybrowser$open()
  mybrowser$setImplicitWaitTimeout(milliseconds=20000) # 1000 milliseconds = 1 second
  mainwindow<-mybrowser$getCurrentWindowHandle()[[1]]
  mybrowser$navigate(url)
  using<-usingpath[1:length(usingpath) %% 2 !=0]
  value<-usingpath[1:length(usingpath) %% 2 ==0]
  for (j in 1:length(using)){
    # Find all Windows (main and children)
    windows<-mybrowser$getWindowHandles()
    if (length(windows)>1){
      for (childwindow in windows){
        # Swtich to Child Window
        if (childwindow!=mainwindow){mybrowser$switchToWindow(childwindow)}
      }}
    # Check if element exists
    #webElem<-try(mybrowser$findElement(using=using[j],value=value[j]),silent=TRUE)
     webElem<-mybrowser$findElement(using=using[j],value=value[j])
    webElem$clickElement()
    pause(10)}

**Comment by johndharrison** [comment]
Please fill out the issue template when posting an issue

**Comment by msgoussi** [comment]
Dear Mr. John

I rewrite my code, so it will be easy for you to understand the problem. please consider mybrowser as remoteDriver. Once you the search button is clicked, a logo/window of "your request is being proceeded" is loading which causes the problem of not finding the element.
I can use pause for 10 seconds, but time for processing data is different from one website to another and from one computer to another.


url<-"http://ppi.worldbank.org/explore/Report.aspx?mode=1"
mybrowser$open()
mybrowser$setImplicitWaitTimeout(milliseconds=60000) # 1000 milliseconds = 1 second
mybrowser$setTimeout("page load",milliseconds=60000)
mybrowser$navigate(url)
mybrowser$findElement(using="xpath",value="//*/input[@name='reporttype'][@value='2']")$clickElement()
mybrowser$findElement(using="xpath",value="//div[@class='advanced-report-selection']/div[1]/div[2]/select//option[@value='1']")$clickElement()
mybrowser$findElement(using="xpath",value="//div[@class='advanced-report-selection']/div[2]/select[1]//option[27]")$clickElement()
mybrowser$findElement(using="xpath",value="//table[@class='select-block']/tbody/tr/td[2]/select//option[5]")$clickElement()
mybrowser$findElement(using="xpath",value="//table[@class='select-block']/tbody/tr/td[4]/select//option[4]")$clickElement()
mybrowser$findElement(using="xpath",value="//table[@class='select-block']/tbody/tr/td[6]/select//option[3]")$clickElement()
mybrowser$findElement(using="xpath",value="//table[@class='select-block']/tbody/tr/td[8]/select//option[8]")$clickElement()
mybrowser$findElement(using="xpath",value="//div[@class='primary-sector']/div[3]/ul/li[1]/label/input")$clickElement()
mybrowser$findElement(using="xpath",value="//div[@class='primary-sector']/div[4]/ul/li[1]/label/input")$clickElement()
mybrowser$findElement(using="xpath",value="//div[@class='primary-sector']/div[5]/ul/li[1]/label/input")$clickElement()
mybrowser$findElement(using="link text",value="Choose Countries")$clickElement()
mybrowser$findElement(using="xpath",value="//li[@class='second']//label[.=' Use country list']")$clickElement()
mybrowser$findElement(using="link text",value="Search")$clickElement()
**mybrowser$findElement(using="link text",value="Download to Excel")$clickElement()**

**Comment by johndharrison** [comment]
Please see #92 . In summary, your element may not be visible, the page is getting refreshed before it is clicking the element or the element is clickable but there is a spinner/overlay on top of it.
