### ISSUE TITLE
PhantomJS 2.5.0 beta

### ISSUE THREAD

**Issue by michaelsbradleyjr** [ropensci/RSelenium#117]
Binaries are shipping now for PhantomJS `2.5.0-beta`. I tried naively dropping it in place of `2.1.1` but was unable, so far, to use it successfully with the current release of `RSelenium`. That could be owing to changes in how RSelenium will need to interact with the process, and/or changes in phantom's page-API that are causing my scripts to blow up... it's not clear yet.

In any case, a number of improvements are touted for `2.5.0`, so it would be nice to be able to take advantage of them.

**Comment by johndharrison** [comment]
Hi Michael. I have tried just now with windows and phantomjs 2.5.0. I am driving phantomjs directly (the equivalent of using the `phantom` function in the `RSelenium` package. It is working for the basic tests I have tried. I would note that ghostdriver is still version 1.2.0 however. I believe phantomjs 2.5.0 will contain an updated version of ghostdriver in time.

**Comment by michaelsbradleyjr** [comment]
I too was/am driving it directly, i.e. by way of the `phantom` function. After tinkering a bit, it *seems *certain operations under `2.5.0-beta` may be *async* whereas previously they were synchronous. For example, `driver$navigate(someUrl)` returns immediately but there's a slight delay before one can successfully do `$findElements()` operations, or `$screenshot()`. With `2.1.0`, navigation didn't return until the page was loaded.

Anyway, what I'm noting above is just guessing on my part. I can succeessfully spawn a `2.5.0` instance and setup a direct-driver with `RSelenium`, as before, but most of my scripts don't work because they assume many of the driver methods will be synchronous, and they now seem not to be.

**Comment by johndharrison** [comment]
Yes I think we would need to wait until ghostdriver is updated:

>  What's inside:
> 
> - bug fixes
> - new command line options (disabling local storage)
> - upgraded Qt to 5.7.1
> - ... Absolutely new and shiny QtWebKit! With full ES2015 support, native promises, JavaScript engine improvements and much more! Here is the comparison table  https://github.com/annulen/webkit/wiki/Comparison-with-QtWebKit-5.6
> - Now you can build PhantomJS against the system-installed Qt
> - support for WEBP format
> 
> More features incoming: updated Ghostdriver (finally!), more improvements on web engine, etc.
> 
>

**Comment by johndharrison** [comment]
Closing this for now. Once an updated ghostdriver becomes available will look at how 2.5.0-beta is progressing
