### ISSUE TITLE
subprocess library, for a better phantom()

### ISSUE THREAD

**Issue by michaelsbradleyjr** [ropensci/RSelenium#118]
See:  [subprocess](https://github.com/lbartnik/subprocess) by Łukasz Bartnik. Also [on CRAN](https://cran.r-project.org/web/packages/subprocess/).

I've been experimenting with a variant of  the `RSelenium::phantom` function:

```R
phantom <- function(pjs_cmd = "", port = 4444L, extras = "", ...) {
  pjs_path <- ""
  if (!nzchar(pjs_cmd)) {
    pjs_path <- Sys.which("phantomjs")
  }
  else {
    pjs_path <- pjs_cmd
  }
  if (nchar(pjs_path) == 0) {
    stop("PhantomJS binary not located.")
  }
  pjs_args <- c(paste0("--webdriver=", port), extras)
  subprocess::spawn_process(pjs_path, pjs_args)
}
```

It's then possible and easy to interact with subprocess instance it returns, by using the library's API, e.g. `subprocess::process_terminate`.

If there's interest, I could look at putting together a pull request.

**Comment by johndharrison** [comment]
Hi michael,

Yes I have seen subprocess. I have asked Lukasz about a number of issues. Hopefully an updated version will
be submitted to CRAN (Lukasz has added OSX support https://github.com/lbartnik/subprocess/issues/21 which would be great).

I had intended on moving all the server related stuff to a separate package. The idea would be that this
package would manage binaries relating to the selenium/webdriver project. At the moment this 
includes:

- selenium server

- chromedriver

- phantomjs binary

- geckodriver

- iedriver

I have added this functionality to a package https://github.com/johndharrison/wdman .  Currently it has
a number of functions which manage the above binaries. If you are interested it would be really useful to have any input on this package.

**Comment by michaelsbradleyjr** [comment]
Ah, yes, I got excited about `subprocess` and failed to notice that you had submitted a number of GitHub issues for the same. I just now noticed that you opened an issue re: its use on macOS. I have been using `subprocess` on my mac laptop (sierra) successfully, and was able to install both from source (via `devtools`) and CRAN.

**Comment by johndharrison** [comment]
Yeah Michael your right. I see subprocess was updated to CRAN yesterday (version 0.8.0). Good news!!

**Comment by johndharrison** [comment]
The [wdman](https://cran.r-project.org/package=wdman) package has now been released to CRAN. 
It includes a phantomjs function which replaces RSelenium::phantom.

**Comment by michaelsbradleyjr** [comment]
I've been using the latest `Rselenium` release since yesterday, making use too of `wdman::phantom`. I haven't had time to file a proper bug report yet, but it seems that for `wdman::phantom` if `check = TRUE` (the default) and it's called concurrently (e.g. in a `%dopar% { ... }` context) failures are triggered. The problem goes away if the concurrent calls have `check = FALSE`.

**Comment by johndharrison** [comment]
@michaelsbradleyjr Interesting do you have minimal reproducible example. There is a new release of `wdman` 0.2.1 but it mostly effects windows OS ( i guess you are using OSX).

**Comment by michaelsbradleyjr** [comment]
I don't have such an example yet, but can put one together.  Yes, I'm using macOS Sierra.
