### ISSUE TITLE
Can not use RSelenium

### ISSUE THREAD

**Issue by msgoussi** [ropensci/RSelenium#119]
Since Firefox version 48, Mozilla requires all add-ons to be signed. Until
recently, Firefox support in Selenium was exclusively provided by an add-on.
As this add-on is not currently signed, this solution does not work with the
latest Firefox releases. As an alternative, Mozilla are working on a WebDriver
specification compliant implementation named GeckoDriver. Please note that the specification is not complete, and that Selenium itself does not comply with
the specification at this time. This means that features previously available
through Selenium will not be available using GeckoDriver.

Currently we would advise against using the latest firefox/geckodriver with selenium untill the w3c webdriver specification
is complete. If you wish to use firefox we would advise using an older version via a Docker image. See the RSelenium
Docker vignette for more detail:

http://rpubs.com/johndharrison/RSelenium-Docker

If your issue is not with geckodriver/firefox please fill out the template

### Operating System
Windows 7
### Selenium Server version (selenium-server-standalone-3.0.1.jar etc.)
3.0.1
### Browser version (firefox 50.1.0, chrome 54.0.2840.100 (64-bit) etc.)
Chrome 55.0.2883.87 
### Other driver version (chromedriver 2.27, geckodriver v0.11.1, iedriver x64_3.0.0, PhantomJS 2.1.1 etc.)
chromedriver 2.27.440174
### Steps to reproduce the behaviour
 rD <- rsDriver()
checking Selenium Server versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
checking chromedriver versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
checking geckodriver versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
Error in jvmargs[["gecko"]] <- sprintf("-Dwebdriver.gecko.driver=%s",  : 
  replacement has length zero

Ps. I just updated the RSelenium package and I got this error.

**Comment by SiegHartR** [comment]
If I run the 1.6.2 version everything is fine, but if I run the latest release (1.7.0) is awfully slow and really different to run smoothly.

Now I'm forced to modify my function which run RSelenium and need to use "rD <- rsDriver()" or download Docker. Much better the oldest version and much quicker with less problems. 

Some commands like $clickElement() with no reason at one point they just stop to run. But going back to the oldest version everything works nice and smoothly.

The 1.7.0 needs IMHO to be improved a lot or provide better instructions on the changes required.

**Comment by johndharrison** [comment]
@msgoussi can you run 

```
wdman::selenium(retcommand = TRUE)
```
with output

then also give the output of

```
binman::list_versions("geckodriver")
```

**Comment by johndharrison** [comment]
@SiegHartR can you please file an issue with the wdman package
