### ISSUE TITLE
A little bug in rsDriver

### ISSUE THREAD

**Issue by bourdieu** [ropensci/RSelenium#123]
The function rsDriver in this line (the bold) part should be **check**, otherwise the **check** value of function `rsDriver` is useless at all.

selServ <- wdman::selenium(port = port, verbose = verbose, 
                             version = version, chromever = chromever, geckover = geckover, 
                             iedrver = iedrver, phantomver = phantomver, check = **ture**)

**Comment by johndharrison** [comment]
@bourdieu thank you for spotting this. I will post a commit to address this

**Comment by johndharrison** [comment]
Fixed 8667b1ab7074ee535588d8182ea61f8e698fd54b
