### ISSUE TITLE
rsDriver issue with PhantomJS

### ISSUE THREAD

**Issue by leehbi** [ropensci/RSelenium#125]
### Operating System
Linux Mint 18.1
### Selenium Server version (selenium-server-standalone-3.0.1.jar etc.)
3.1
### Browser version (firefox 50.1.0, chrome 54.0.2840.100 (64-bit) etc.)
PhantomJs 2.1.1
### Expected behaviour
rd <-rsDriver(verbose =TRUE, browser = 'phantomjs')  should return client/server
### Actual behaviour
Command returns error when connecting to server.

Selenium message:org.openqa.selenium.os.CommandLine.find(Ljava/lang/String;)Ljava/lang/String;

Error: 	 Summary: UnknownError
 	 Detail: An unknown server-side error occurred while processing the command.
 	 class: java.lang.NoSuchMethodError
	 Further Details: run errorDetails method

**Comment by johndharrison** [comment]
@leehbi Thank you for bringing this to my attention. This seems to be an issue with the latest version of selenium server. If you try the previous version the error doesn't appear:

```
rd <-rsDriver(verbose =TRUE, browser = 'phantomjs', version = "3.0.1")
```

**Comment by johndharrison** [comment]
Issue submitted to the Selenium project https://github.com/SeleniumHQ/selenium/issues/3534

**Comment by johndharrison** [comment]
>  lmtierney commented 7 hours ago

> Hi, this is due to the removal of a deprecated method being removed in 3.1. I've made the change with the ghostdriver bindings codeborne/ghostdriver#3. Once they do a new release, then we can pull in the new version into the third-party directory. Keep in mind for standalone to work after that there would need to be a new release, unless you built the standalone server yourself

**Comment by johndharrison** [comment]
Selenium Server 3.2.0 is now released and this issue is addressed.
