### ISSUE TITLE
Getting unable to find free port in remote server while running the build in Jenkins

### ISSUE THREAD

**Issue by chaithanyvv** [ropensci/RSelenium#126]
Please provide a code in Java to release the port after each build.
We have integrated maven with Jenkins and in the PhantomJS Driver.java
    private PhantomJSDriverService(File executable,
                                   int port,
                                   ImmutableList<String> args,
                                   ImmutableMap<String, String> environment) throws IOException {
        super(executable, port, args, environment);

        // Print out the parameters used to launch PhantomJS Driver Service
        LOG.info("executable: " + executable.getAbsolutePath());
        LOG.info("port: " + port);
        LOG.info("arguments: " + args.toString());
        LOG.info("environment: " + environment.toString());
    }
When the phantomjs browser is startet from maven, it is always using the same port for communication.

/opt/SP/apps/phantomjs-2.1.1-linux-x86_64/bin/phantomjs --webdriver=1024

Please provide a solution or java code to be included so that after each build the port is released..

**Comment by johndharrison** [comment]
Is this issue for the Selenium project?
