### ISSUE TITLE
Don't print serverURL when using saucelabs

### ISSUE THREAD

**Issue by jstockwin** [ropensci/RSelenium#128]
### Operating System
Ubuntu 16:04
### Selenium Server version (selenium-server-standalone-3.0.1.jar etc.)
Saucelabs
### Browser version (firefox 50.1.0, chrome 54.0.2840.100 (64-bit) etc.)
N/A
### Other driver version (chromedriver 2.27, geckodriver v0.11.1, iedriver x64_3.0.0, PhantomJS 2.1.1 etc.)
N/A
### Actual behaviour

I was experimenting with running Sauce Connect myself on travis, rather than using their inbuilt way of doing things. Anyway, I messed up slightly and didn't wait for the tunnel to finish creating before using it. This resulting in a connection error, and the code [here](https://github.com/ropensci/RSelenium/blob/master/R/errorHandler.R#L179) printed the serverURL to the travis console. The URL looks like `username:access-key@saucelabs...` and so it pasted my access key into the terminal. 

### Expected behaviour

The access key should be starred out, or something else to obscure it. 

### Steps to reproduce the behaviour

Try to connect to a sauce tunnel which you haven't actually started.

**Comment by johndharrison** [comment]
Hi Jake,

Thanks for picking up on this. The `serverURL` string could be parsed using something like `httr::parseURL`,
breaking it down to its constituents then rebuilding using `httr::build_url` with username and password replaced with e.g. ****. `parseURL` basically uses regular expressions so could use a bespoke regex or something similar instead

```
user <- "rselenium0"
pass <- "mypass"
port <- 80
ip <- paste0("http://", user, ':', pass, "@ondemand.saucelabs.com")
> ip
[1] "http://rselenium0:mypass@ondemand.saucelabs.com"
parsedip <- httr::parse_url(ip)
parsedip$username <- "****"
parsedip$password <- "****"
httr::build_url(parsedip)
[1] "http://****:****@ondemand.saucelabs.com/"
```

Pull requests are welcome!!

**Comment by jstockwin** [comment]
Hi John, 

Thanks for the pointers. See the above PR and let me know if you'd like me to change anything. 

Thanks!
