### ISSUE TITLE
Issues using RSelenium using command line (Rscript.exe)

### ISSUE THREAD

**Issue by justinbirmingham** [ropensci/RSelenium#129]
If your issue is not with geckodriver/firefox please fill out the template

### Operating System
Windows Server 2012 R2 Standard

### Selenium Server version (selenium-server-standalone-3.0.1.jar etc.)
Not sure, using rsDriver in script

### Browser version (firefox 50.1.0, chrome 54.0.2840.100 (64-bit) etc.)
Chrome 57.0.2987.133 (64-bit)

### Other driver version (chromedriver 2.27, geckodriver v0.11.1, iedriver x64_3.0.0, PhantomJS 2.1.1 etc.)
Chromedriver 2.29.461591

### Expected behaviour
R script that runs fine in RStudio should also run using Rscript.exe

### Actual behaviour
Get error when trying to use findElement method

![rscript error](https://cloud.githubusercontent.com/assets/1953434/25394179/2125d470-29a3-11e7-9fb7-60333a8c53bf.PNG)

### Steps to reproduce the behaviour
#Run below script using command line Rscript.exe

library('RSelenium')

#Start Selenium Server
rD <- rsDriver(port = as.integer(4443), browser = "chrome", verbose = TRUE)
remDr <- rD[["client"]]
remDr$navigate("https://www.google.com/")

webElement <- remDr$findElement('xpath', '//*[@id="lst-ib"]')
webElement$sendKeysToElement(list("test"))

remDr$close()
rD[["server"]]$stop()

**Comment by eufmike** [comment]
"is" in the "Methods" package should be inherent, but cannot run with Rscript for some reason. Add `library(methods)` resolved this issue.

**Comment by JetRockEnergy** [comment]
Thanks eufmike, that worked.
