### ISSUE TITLE
Can't move to new window handle using remDr$switchToWindow

### ISSUE THREAD

**Issue by mislav0207** [ropensci/RSelenium#143]
am using RSelnium package ti scrape some data. I have problem with moving on another window when it pop up.

Here is the code:
```
library(RSelenium)

rD <- rsDriver(browser = "firefox")
remDr <- rD$client

# Simulate browser session and fill out form
remDr$navigate("http://www.dziv.hr/hr/e-usluge/pretrazivanje-baza-podataka/medjunarodni-zig/")
Sys.sleep(2)
webElem <- remDr$findElements("css", "iframe")
remDr$switchToFrame(webElem[[1]])
webel <- remDr$findElement(using = "xpath", "//input[@id = 'TB1']")$sendKeysToElement(list(as.character("*"), key = "enter"))
# HERE NEW WINDOW APPEARS
Sys.sleep(4)
# try to switch to new window
windows_handles <- remDr$getWindowHandles()
Sys.sleep(1)
remDr$switchToWindow(windows_handles[[2]])
```
Even if I try to awitch to new window nothin happens. For example, if I try the code:

htmlParse(remDr$getPageSource()[[1]], encoding = "UTF-8")

it parses first, not the second window.
It somehow cant recognize second window.

**Comment by johndharrison** [comment]
This issue is due to changes in the underlying API of the driver (geckodriver) which firefox uses.
geckodriver is gradually implementing adherence to the w3c webdriver spec. This has a lot of similarity to
the old JSONwireprotocol underlying selenium but diverges in places. Window handles is where such divergence occurs.

For example:

```
myswitch <- function (remDr, windowId) 
{
  qpath <- sprintf("%s/session/%s/window", remDr$serverURL, 
                   remDr$sessionInfo[["id"]])
  remDr$queryRD(qpath, "POST", qdata = list(handle = windowId))
}

remDr$navigate("http://www.dziv.hr/hr/e-usluge/pretrazivanje-baza-podataka/medjunarodni-zig/")
Sys.sleep(2)
webElem <- remDr$findElements("css", "iframe")
remDr$switchToFrame(webElem[[1]])
webel <- remDr$findElement(using = "xpath", "//input[@id = 'TB1']")$sendKeysToElement(list(as.character("*"), key = "enter"))

# try to switch to new window
check_handle <- FALSE
count <- 0
while(!check_handle || count > 20){
  count <- count + 1
  windows_handles <- remDr$getWindowHandles()
  if(length(windows_handles) < 2){
    Sys.sleep(1)
  }else{
    check_handle <- TRUE
  }
}
myswitch(remDr, windows_handles[[2]])
```
should allow you to switch windows. 

Unfortunately currently there is no obviouys indicator of the webdriver specification expected by the server. I will look to give the user the option to use W3C spec until a better option is available.

**Comment by mislav0207** [comment]
I haven't understand most of what you were saying, but the code is working.

Thank you very much for help. I have spent 5 hours trying to find the solution.

Best!

**Comment by mislav0207** [comment]
I have a problem again. I suppose it is connected with your previous answer. I cant execute script on page.

After previous code:
```
rm(list = ls())

library(RSelenium)


# functions
myswitch <- function (remDr, windowId) 
{
  qpath <- sprintf("%s/session/%s/window", remDr$serverURL, 
                   remDr$sessionInfo[["id"]])
  remDr$queryRD(qpath, "POST", qdata = list(handle = windowId))
}



#RSelenium::startServer()
rD <- rsDriver(browser = "firefox")
remDr <- rD$client
remDr$open()

# Simulate browser session and fill out form
remDr$navigate("http://www.dziv.hr/hr/e-usluge/pretrazivanje-baza-podataka/medjunarodni-zig/")
Sys.sleep(2)
webElem <- remDr$findElements("css", "iframe")
remDr$switchToFrame(webElem[[1]])
webel <- remDr$findElement(using = "xpath", "//input[@id = 'TB1']")$sendKeysToElement(list(as.character("*"), key = "enter"))
Sys.sleep(5)

# try to switch to new window
check_handle <- FALSE
count <- 0
while(!check_handle || count > 20){
  count <- count + 1
  windows_handles <- remDr$getWindowHandles()
  if(length(windows_handles) < 2){
    Sys.sleep(1)
  }else{
    check_handle <- TRUE
  }
}
myswitch(remDr, windows_handles[[2]])
```
I wanted to collect data from every page through 1 to te end. I have a loop:
```
links_all <- list()
for (i in 1:6292) {
  if (i == 1){
    doc <- htmlParse(remDr$getPageSource()[[1]], encoding = "UTF-8")
    Sys.sleep(3)
    links_all[[i]] <- getHTMLLinks(doc)
  }else{
    remDr$executeScript(paste0("__doPostBack(","'GVRezultati',", "'Page$", i, "');"))
    doc <- htmlParse(remDr$getPageSource()[[1]], encoding = "UTF-8")
    Sys.sleep(3)
    links_all[[i]] <- getHTMLLinks(doc)
    Sys.sleep(2)
  }
  }
```
It seems to me that I shouldn't use Firefox with Selenium anymore because I will have some kind of problems all along.

**Comment by johndharrison** [comment]
Until the w3c spec is completed and geckodriver API unchanged it maybe easier to use chrome. Alternatively you can use a legacy version of firefox via a docker image.

**Comment by mislav0207** [comment]
I tried to use chrome:
`rD <- rsDriver(browser = "chrome")`

but it returns an error:

> [1] "Connecting to remote server"
> 
> Selenium message:unknown error: unable to discover open pages
>   (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 60.13 seconds
> Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
> System info: host: 'MISLAV-PC', ip: '169.254.169.234', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
> Driver info: driver.version: unknown
> 
> Could not open chrome browser.
> Client error message:
> 	 Summary: UnknownError
>  	 Detail: An unknown server-side error occurred while processing the command.
> 	 Further Details: run errorDetails method
> Check server log for further details.

I have installed chrome driver and add it to system path, but it returns above error.
I don't know how to fix it?

**Comment by mislav0207** [comment]
I have now also tied to use Firefox via Docker and I got an error:

> Error: 	 Summary: UnknownError
>  	 Detail: An unknown server-side error occurred while processing the command.
>  	 class: java.lang.NullPointerException
> 	 Further Details: run errorDetails method

**Comment by taiyodayo** [comment]
Thank you so much @johndharrison !!!! After days of googling, you saved me too.
Hope you have a wonderful day ahead.

**Comment by caddell** [comment]
Got the same issue with chrome, but the mySwitch() from @johndharrison worked it all out. Thanks!

**Comment by hjsimpso** [comment]
Had this issue in chrome as well. `myswitch()` worked. Thanks @johndharrison !

**Comment by kongdd** [comment]
Had this issue in chrome as well too. myswitch() worked. Thanks @johndharrison !
