### ISSUE TITLE
Connecting to travis local host Rselenium sauce labs 

### ISSUE THREAD

**Issue by adamrobinson361** [ropensci/RSelenium#145]
Hi, 

First thanks for the RSelenium package - i've been playing about with it and it is really useful!

Unfortunately i am having a problem with it when i use it in the following set up:

- Git hub code
- Travis build
- R Selenium with sauce labs to run tests

You can find my repo [here](https://github.com/adamrobinson361/travis) in which i am trying to define a shiny testing workflow. 

The travis file and test-basic.R are all that really make it up besides the standard example shiny app. 

It seems as though sauce labs cant connet to the travis local host using R Selenium.

Any ideas?

Regards,

Adam

**Comment by johndharrison** [comment]
Hi Adam,

Did you use sauce connect?

**Comment by adamrobinson361** [comment]
Hi John, 

Yes i think i used source connect. In the travis.yml i do the following: 
```
addons: 
   sauce_connect: 
      username: $SAUCE_USERNAME 
      access_key: $SAUCE_SECRET_KEY 
```
Similarly in the travis logs it looks to say that its connnected and disconnected from sauce labs correctly. [Link](https://travis-ci.org/adamrobinson361/travis)

**Comment by johndharrison** [comment]
In your remote driver call you need to connect to saucelabs rather than localhost. Any local websites 
called by selenium hosted on saucelabs will use the sauceconnect proxy.
```
~~ip <- paste0(user, ':', pass, "@localhost")~~
ip <- paste0(user, ':', pass, "@ondemand.saucelabs.com")
```

**Comment by adamrobinson361** [comment]
Hi John,

Thanks for your reply. I made the change and initially got a port error that 4445 isn't available for "@ondemand.saucelabs.com". I consulted the documentation and realised that it should be port 80 for this address. Unfortunately even after changing I get the same error I had initially that it cant connect to the server. 

Also, I am a bit confused if your suggestion is the scenario I am in. As per the [sauce labs vignette](https://cran.r-project.org/web/packages/RSelenium/vignettes/RSelenium-saucelabs.html) I would think that I would require the *RSelenium with remote browsers and local sites* scenario. In my mind I am running all the code on travis which is in esscence my machine for this and the site is local to that. I am then trying to connect to a remote browser?

**Comment by johndharrison** [comment]
Hi Adam,

I have cloned your repo and will look at getting it running. Incidentally your credentials are possibly exposed https://github.com/adamrobinson361/travis/blob/master/.Rhistory#L5 .

**Comment by adamrobinson361** [comment]
Thanks John - and thanks for the spot on credentials! I've changed the access key and using as environment variables in travis now so shouldn't be any trouble in the history. 

Regards,

Adam

**Comment by johndharrison** [comment]
Hi Adam.

Apologies you were correct initially. You connect to sauceconnect on localhost:4445 (default sc port) rather than with saucelabs. I added the SAUCE_USERNAME, SAUCE_SECRET_KEY env variables as encrypted values in the yaml file (you may have added them on the travis website directly). 

I changed the shiny port to 3000 (this may not have mattered). The other thing was sauceconnect needed a tunnel identifier as per https://docs.travis-ci.com/user/sauce-connect/. I added this as an extra capability. See https://github.com/johndharrison/travis . 

The test runs as expected now

**Comment by adamrobinson361** [comment]
This looks great! I'd read a little about the tunnel identifier but didn't understand enough how it worked in context of R Selenium. Are you able to let me know if you can see the browser navigating to the shiny app successfully in sauce labs?

Thanks again for your help,

Adam

**Comment by johndharrison** [comment]
Hi Adam,

Try a different browser. Firefox 26 is ancient and is most likely not compatible with the selenium server version saucelabs is running. I switched to chrome 48 with Linux. You can see the current supported platforms on saucelabs at https://saucelabs.com/platforms#linux. 
Here is the test on saucelabs
https://saucelabs.com/beta/tests/3183c4afd0cb4640b0f0184182889640/commands?enabledFilters=hasScreenshot#2

**Comment by adamrobinson361** [comment]
Ah I must've taken that from an old example i'd found somewhere. Changed to chrome 48 and works a charm. 

Thanks very much for your help. Should really help us when developing shiny apps for customers and ensuring they are stable!

Regards,

Adam

**Comment by johndharrison** [comment]
@adamrobinson361 happy to help. Saucelabs is useful as it allows you to see the app as its tested etc and test across a range of platforms and browsers. 

For CI purposes where you are developing a set of tests for your app using Docker on Travis might be useful also. 

- launch a docker container running Selenium and a given browser
- launch a docker container running shiny server/ shinyproxy (www.shinyproxy.io)
- docker containers are linked so can communicate
- all testing done on Travis

See for example https://github.com/ropensci/RSelenium/issues/102

**Comment by adamrobinson361** [comment]
I'll definitely look into that. Thanks again, Adam
