### ISSUE TITLE
unable to create new service

### ISSUE THREAD

**Issue by Elaine9955** [ropensci/RSelenium#146]
Since Firefox version 48, Mozilla requires all add-ons to be signed. Until
recently, Firefox support in Selenium was exclusively provided by an add-on.
As this add-on is not currently signed, this solution does not work with the
latest Firefox releases. As an alternative, Mozilla are working on a WebDriver
specification compliant implementation named GeckoDriver. Please note that the specification is not complete, and that Selenium itself does not comply with
the specification at this time. This means that features previously available
through Selenium will not be available using GeckoDriver.

Currently we would advise against using the latest firefox/geckodriver with selenium untill the w3c webdriver specification
is complete. If you wish to use firefox we would advise using an older version via a Docker image. See the RSelenium
Docker vignette for more detail:

http://rpubs.com/johndharrison/RSelenium-Docker

If your issue is not with geckodriver/firefox please fill out the template

### Expected behaviour
 I would expect that the server runs properly.

### Actual behaviour
> remDr$open() #Open the browser
[1] "Connecting to remote server"
Selenium message:Unable to create new service: ChromeDriverService
Build info: version: '3.5.1', revision: '9c21bb67ef', time: '2017-08-16T21:10:06.092Z'
System info: host: 'CICHGVAL209', ip: '192.168.1.168', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
Error: 	 Summary: SessionNotCreatedException
 	 Detail: A new session could not be created.
	 Further Details: run errorDetails method

### Steps to reproduce the behaviour
As I saw on the other websites, I made sure that the selenium runs. 
Also, I put chromedriver.exe under the same folder as chrome.exe. Then I add the location of the folder which contains these two application into PATH (environment variable).
I used these methods to set up one laptop. However, when I set up another one, everytime I run
>remDr<-remoteDriver(remoteServerAddr = "localhost",port = 4444, browserName = "chrome")
remDr$open() #Open the browser

Then it keeps telling me that "unable to create new service: ChromeDriverService".

**Comment by yupadhye** [comment]
Any update on this? Is this OS specific? I am getting same error.

**Comment by nhack** [comment]
I have the same issue, but I'm using Google Chrome v59 (32-bit), the rest is the same. Any updates?

**Comment by Elaine9955** [comment]
I figured out it after using 32bits chrome instead of 64bits, although the chromedriver should work properly under version which I saw some articles about. 

If using the elder version, it is essential to use the correct version of chromedriver since the chromedriver would not support all versions of chrome.

**Comment by johndharrison** [comment]
Yes chromedriver is tied to certain versions of chrome. You can look into using the rsDriver function which should let you select a version of the chromedriver to use. Alternatively the recommended way to run Selenium is via Docker which would eliminate need to pair drivers to browsers etc.

**Comment by dharshinid-rpx** [comment]
Is there any work around for this error with Firefox ? 

Server is running; Am I missing any? looking forward for guidance here.

Below are my LOC which throws error

> > require(RSelenium)
> > remDr <- remoteDriver(browserName = 'firefox')
> > remDr$open()
> [1] "Connecting to remote server"
> 
> Selenium message:Unable to create new service: GeckoDriverService
> Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
> System info: host: 'IMCHLT058', ip: '000.000.0.0', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '9'
> Driver info: driver.version: unknown
> 
> Error: 	 Summary: SessionNotCreatedException
>  	 Detail: A new session could not be created.
> 	 Further Details: run errorDetails method

**Comment by dharshinid** [comment]
Is there any update on this?  I face similar error with chrome as well, though chrome driver is setup. And, on attempting using rsDriver the Chrome browser gets opened and later throws similar error. So, unable to take further steps. Am I missing any step here, thoughts?

**Comment by encaion** [comment]
I have exactly the same issue. Is there anyone have a solution?

**Comment by joetharayil** [comment]
Getting similar error 

 Error: A new session could not be created.
    at end() - C:\Projects\webdriverio-test\test.js:15:6
  details: undefined,
  message: 'Unable to create new service: ChromeDriverService\nBuild info: version: \'3.8.1\', revision: \'6e95a6684b\', time: \'2017-12-01T19:05:32.194Z\'\nSystem info: host: \'S00452-7480\', ip: \'10.1.40.196\', os.name: \'Windows 10\', os.arch: \'amd64\', os.version: \'10.0\', java.version: \'1.8.0_151\'\nDriver info: driver.version: unknown',
  type: 'RuntimeError',
  seleniumStack:
   { type: 'SessionNotCreatedException',
     message: 'A new session could not be created.',
     orgStatusMessage: 'Unable to create new service: ChromeDriverService\nBuild info: version: \'3.8.1\', revision: \'6e95a6684b\', time: \'2017-12-01T19:05:32.194Z\'\nSystem info: host: \'S00452-7480\', ip: \'10.1.40.196\', os.name: \'Windows 10\', os.arch: \'amd64\', os.version: \'10.0\', java.version: \'1.8.0_151\'\nDriver info: driver.version: unknown' } }

**Comment by brian91dd** [comment]
Same error here

16:58:51] E/launcher - Unable to create new service: ChromeDriverService
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'debian', ip: '192.168.88.253', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-4-amd64', java.version: '1.8.0_151'
Driver info: driver.version: unknown
[16:58:51] E/launcher - SessionNotCreatedError: Unable to create new service: ChromeDriverService
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'debian', ip: '192.168.88.253', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-4-amd64', java.version: '1.8.0_151'
Driver info: driver.version: unknown

**Comment by joetharayil** [comment]
I stopped getting this error after re installed the latest version of chromedriver and added both chrome.exe and chromedriver.exe to the PATH under system variables.

![image](https://user-images.githubusercontent.com/35235047/34846056-c3a364d8-f6cb-11e7-9c9e-d8b657fcac5d.png)

**Comment by encaion** [comment]
I solved this error.

When I upgrade RSelenium library, there was unstable interconnection. So, I stopped that and retry few minutes later. This behavior occur sever error related RSelenium.
Anyway. 

for Windows user.
go to [C:\Users\_your  window account__\AppData\Local\binman]

delete every directories under the [bitman] directory.

maybe these 4 directories exist. (or more)

[binman_chromedriver]
[binman_geckodriver]
[binman_phantomjs]
[binman_seleniumserver]

after this, try re-install RSelenium package.

good luck.

**Comment by kev-landry** [comment]
It may sound obvious but did you update the webdriver-manager ?

`webdriver-manager update
`

**Comment by JanVanIm** [comment]
I do have the same trouble. In a Windows command prompt I run the lines 

`java -Dwebdriver.gecko.driver=" C:\Users\User\Downloads\geckodriver-v0.19.1-win64\geckodriver.exe" -jar selenium-server-standalone-3.11.0.jar`

I get 

>  Selenium Server is up and running on port 4444

But in R i get the same message
I added the PATH of GeckoDriver to Windows's environment variable. 

All the solutions on the Internet seems to rely on running a Java file but I don't know how to run Java code in Windows.

Thanks

**Comment by thevictorian** [comment]
This worked for me:

library(RSelenium)
driver<- rsDriver(browser=c("firefox"))
remDr <- driver[["client"]]
remDr$open()

Thanks to JanVanIm

**Comment by plumtamine** [comment]
@encaion Thank you! Your solution solved my issue. After deleting everything under binman, I changed the version in the rsDriver statement. Then it worked. ( BTW, I am using it on Chrome)

**Comment by GohBoonHong** [comment]
i try @JanVanIm  answer ,but  also error  , results >>  checking chromedriver versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
checking geckodriver versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
checking phantomjs versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
BEGIN: POSTDOWNLOAD
Error in if (file.access(phantompath, 1) < 0) { : 
  argument is of length zero

**Comment by GohBoonHong** [comment]
who can help me ?

**Comment by RolandoHsu** [comment]
i get the same question when i try @JanVanIm's answer, plz help me QQ

**Comment by GohBoonHong** [comment]
Dear ,

        can i help you ?

best ,
Johnson

**Comment by RolandoHsu** [comment]
Good morning Johnson,

I found the problem coming from the version of chrome,
so I updated my chrome to version 77 and solved this question,
really thank you to help me,

best regards,

Rolando

boonhong <notifications@github.com> 於 2019年8月23日 週五 上午9:49寫道：

> Dear ,
>
> can i help you ?
>
> best ,
> Johnson
>

**Comment by GohBoonHong** [comment]
thank YOU
