### ISSUE TITLE
Problem with webSockets

### ISSUE THREAD

**Issue by johndharrison** [ropensci/RSelenium#15]
Running the test app on one R session:

require(shiny)

> packageVersion('shiny')
> [1] ‘0.9.1’

runApp(file.path(find.package("RSelenium"), "apps", "shinytestapp"), port = 3000)

Running [sauceConnect](https://saucelabs.com/docs/connect) in a windows shell: 
C:\Users\john\Documents\sc-4.1-win32\bin>sc.exe -u rselenium0 -k 49953c74-5c46-4
ff9-b584-cf31a4c71809 -v

```
require(RSelenium)
user <- "rselenium0" # Your Sauce Labs username
pass <- "49953c74-5c46-4ff9-b584-cf31a4c71809" # Your Sauce Labs access key 
```

~~port <- 80~~
~~ip <- paste0(user, ':', pass, "@ondemand.saucelabs.com")~~

```
port <- 4445
ip <- paste0(user, ':', pass, "@localhost")
rdBrowser <- "firefox"
version <- "26"
platform <- "Linux"
extraCapabilities <- list(name = "RSelenium OS/Browsers vignette second example", username = user
                          , accessKey = pass, tags = list("RSelenium-vignette", 
                                                          "OS/Browsers-vignette", "Example 2"))
remDr <- remoteDriver$new(remoteServerAddr = ip, port = port, browserName = rdBrowser
                          , version = version, platform = platform
                          , extraCapabilities = extraCapabilities)
```

Run a basic script:

```
localScript <- function(remDr){
  remDr$open()
  remDr$setImplicitWaitTimeout(2000) # wait for elements for 2 seconds
  remDr$navigate("http://localhost:3000")
  Sys.sleep(2)
  # highlight the labels
  webElems <- remDr$findElements("css selector", "#ctrlSelect span")
  lapply(webElems, function(x){x$highlightElement()})
  Sys.sleep(2)
  appIds <- c("summary", "distPlot", "ggPlot", "dttable")
  # Click each checkbox and check for its output
  lapply(seq_along(webElems), function(x){
    if(!webElems[[x]]$isElementSelected()[[1]]){
      webElems[[x]]$clickElement()
      # test for its output
      out <- remDr$findElement("id", appIds[x])
      out$highlightElement()
    }
  })

  remDr$close()
}

localScript(remDr)
```

Remote server connects locally but webSockets appear to be playing up.
Can be seen at project page https://saucelabs.com/u/rselenium0
search for name `Browsers vignette second example` video shows the shiny app greying out.

SAUCE CONNECT LOGS SHOW
20140414 202528.972 [06644] KGP warning: no keepalive ack for > 5s
20140414 202529.972 [06644] KGP warning: no keepalive ack for > 5s
20140414 202530.974 [06644] KGP warning: no keepalive ack for > 5s
20140414 202531.975 [06644] KGP warning: no keepalive ack for > 5s
20140414 202532.976 [06644] KGP warning: no keepalive ack for > 5s

which corresponds to this test https://saucelabs.com/tests/f74fbaa0d296404ab4dfe9e4a5baf36e

**Comment by tinw** [comment]
Can anyone tell me if this solution is still valid? Currently on SauceConnect version 4.3.9.

**Comment by theCampbell** [comment]
@tinw , Using the Varnish VM should no longer be needed but disabling encrypted caching is.  To disable this add '-B all' to the argument list when starting Sauce Connect or if you would like to be more precise list the domains in a comma separated list (EG, -B myWebsite.com,myOtherWebsite.com).  This should allow for socketed communication to complete and if not please let me know.
