### ISSUE TITLE
How to set chrome User Agent to visit mobile web

### ISSUE THREAD

**Issue by wzrzt** [ropensci/RSelenium#159]
I' m trying to use chrome webdriver to crawl data from mobile website and if I use url that begin with "m.",  it  is not stable, the page often jump to PC page.  So I must manually set user agent to iPhone or others. I saw that in python selenium they can set user agent by change chromeoptions but I find nothing when searching on google. Can anyone help me? Thanks.

**Comment by johndharrison** [comment]
```
library(RSelenium)
eCaps <- list(chromeOptions = list(
  args = list('--user-agent="myuseragent"')
))
rD <- rsDriver(extraCapabilities = eCaps)
remDr <- rD$client
remDr$navigate("http://www.google.com")
> remDr$executeScript("return navigator.userAgent;", list(""))
[[1]]
[1] "\"myuseragent\""
#####
# cleanup
rm(rD)
gc()

```

**Comment by wzrzt** [comment]
@johndharrison Thank you very much, It works fine !  And excuse me, I didn't find any document about "extraCapabilities" here in this repository or google. Could you please show us some document about it. With the help of rvest and tydyverse, it's much faster to analyze data crawled from Internet. So I believe that more and more data people would like to use RSelenium. And the document will help us R users a lot.  Thank you again!
