### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by zappingseb** [ropensci/RSelenium#181]
Hi @juyeongkim , we are using the RSelenium package at @Roche and would like to support you developing the package. We have some wrapper functions for getting images etc and are also not really happy with the installation process of the package on Windows. Can we collaborate on this?

**Comment by stefaniebutland** [comment]
Thanks for getting in touch @zappingseb!

**Comment by juyeongkim** [comment]
Hi @zappingseb! That's wonderful to hear, and thank you for reaching out. What do you have in mind? If it's easier, we could set up time to chat.

**Comment by zappingseb** [comment]
Hi. Yeah, shall we arrange a hangouts-meet? That's the easiest for me. Or do you guys have a slack channel you could invite me to? I'm free 23rd of August (8am - 3pm CET) 24th of August basically the whole day

**Comment by stefaniebutland** [comment]
Hi @zappingseb. I can send you an invitation to rOpenSci Slack as a package contributor. What email address shall I send to ?

**Comment by zappingseb** [comment]
Zappingseb {at} Gmail would be great

**Comment by juyeongkim** [comment]
24th (friday) works for me
