### ISSUE TITLE
Documentation about passing arguments (user-agent for example) to Firefox 

### ISSUE THREAD

**Issue by reyman** [ropensci/RSelenium#183]
### Operating System
Ubuntu

### Selenium Server version (selenium-server-standalone-3.0.1.jar etc.)
Docker selenium/standalone-firefox:3.14.0-arsenic

### Browser version (firefox 50.1.0, chrome 54.0.2840.100 (64-bit) etc.)
Firefox 61.0

### Other driver version (chromedriver 2.27, geckodriver v0.11.1, iedriver x64_3.0.0, PhantomJS 2.1.1 etc.)

I search documentation to change the "user-agent" string using Firefox and RSelenium. I see nothing about that.

I try this, without success 

```
eCaps <- list(`mox:firefoxOptions` = list(general.useragent.override="bla"))
remDr <- remoteDriver(remoteServerAddr = "localhost", port = 4445L, extraCapabilities = eCaps )
remDr$open()
remDr$executeScript("return navigator.userAgent;", list(""))
```

Do you have a working example on that ?

**Comment by juyeongkim** [comment]
@reyman, try `makeFirefoxProfile()`:

```R
fprof <- RSelenium::makeFirefoxProfile(list(general.useragent.override = "bla"))

remDr <- RSelenium::remoteDriver(
  remoteServerAddr = "localhost",
  port = 4445L,
  extraCapabilities = eCaps
)
remDr$open()

remDr$executeScript("return navigator.userAgent;", list(""))
```
