### ISSUE TITLE
How to use headless with modern Geckodriver Firefox

### ISSUE THREAD

**Issue by MartinEden** [ropensci/RSelenium#184]
Could this be added to the docs / vignettes. It took me several hours to get right:

```
driver <- RSelenium::remoteDriver(
    browserName = "firefox",
    extraCapabilities = list("moz:firefoxOptions" = list(
        args = list('--headless')
    ))
)
```

I launched the server with this bash script:

```
SELENIUM_VERSION=3.9.1
SELENIUM_FILE=selenium-server-standalone-$SELENIUM_VERSION.jar
if [ ! -f "$SELENIUM_FILE" ]; then
    wget http://selenium-release.storage.googleapis.com/3.9/$SELENIUM_FILE
fi
java -jar $SELENIUM_FILE
```

**Comment by juyeongkim** [comment]
Thank you @MartinEden! I am planning on re-writing the headless vignette and will add this to the new vignette.

From setting up to tearing down via only `RSelenium`:

```R
rD <- RSelenium::rsDriver(
  browser = "firefox",
  extraCapabilities = list(
    "moz:firefoxOptions" = list(
      args = list('--headless')
    )
  )
)
remDr <- rD$client
remDr$open()
remDr$nagivate("https://www.google.com")
remDr$screenshot(display = TRUE)
remDr$close()
rD$server$stop()
```

**Comment by MartinEden** [comment]
You're welcome. Thank you for the package :)

**Comment by gueyenono** [comment]
> Thank you @MartinEden! I am planning on re-writing the headless vignette and will add this to the new vignette.
> 
> From setting up to tearing down via only `RSelenium`:
> 
> ```r
> rD <- RSelenium::rsDriver(
>   browser = "firefox",
>   extraCapabilities = list(
>     "moz:firefoxOptions" = list(
>       args = list('--headless')
>     )
>   )
> )
> remDr <- rD$client
> remDr$open()
> remDr$nagivate("https://www.google.com")
> remDr$screenshot(display = TRUE)
> remDr$close()
> rD$server$stop()
> ```

Has anything changed? I am trying to run this code and I get the following error when I run the script for navigating to google.com:

```
Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  ‘nagivate’ is not a valid field or method name for reference class “remoteDriver”
```
