### ISSUE TITLE
Devtools dependency not explicit

### ISSUE THREAD

**Issue by davidkleman** [ropensci/RSelenium#186]
### Operating System
Ubuntu 18.04

### Browser version (firefox 50.1.0, chrome 54.0.2840.100 (64-bit) etc.)
ff 62.0.3
chrome 63.0.3497.100

### Other driver version (chromedriver 2.27, geckodriver v0.11.1, iedriver x64_3.0.0, PhantomJS 2.1.1 etc.)
NA

### Expected behaviour
start rsDriver()

### Actual behaviour
checking Selenium Server versions:
BEGIN: PREDOWNLOAD
BEGIN: DOWNLOAD
Creating directory: /home/david/.local/share/binman_seleniumserver/generic/3.12.0
Downloading binary: https://www.googleapis.com/download/storage/v1/b/selenium-release/o/3.12%2Fselenium-server-standalone-3.12.0.jar?generation=1525792556725818&alt=media

Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.

I solved this by install.packages("devtools"), but it took some time to figure out.

**Comment by wush978** [comment]
After checking the dependencies of `devtools` one by one, `stringi` is the package which removes this bug.

**Comment by law1618** [comment]
> After checking the dependencies of `devtools` one by one, `stringi` is the package which removes this bug.

I installed stringi and tried again with no luck. Is there any further step?

**Comment by lazycipher** [comment]
Anyone got it working?
I'm facing the same issue.

**Comment by Joaobazzo** [comment]
I couldnt make it work well

**Comment by stragu** [comment]
I was having the same issue:

> Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
> Unrecognized content encoding type. libcurl understands deflate, gzip content encodings.

Installing stringi again (from source) with `install.packages("stringi")` did help to some extent, as the error didn't come back, but I got stuck further down with:

> BEGIN: POSTDOWNLOAD
Error in (function (platform, file, processed, chmod)  : 
> /home/stragu/.local/share/binman_geckodriver/linux64/0.27.0/geckodriver-v0.27.0-linux64.tar.gz.asc does not appear to be a zip or tar file.

I guess it's trying to deal with `geckodriver-v0.27.0-linux64.tar.gz` but catches the signature file `geckodriver-v0.27.0-linux64.tar.gz.asc` instead...

Any idea what might the next step be here?

Using:
- R 4.0.2
- RSelenium 1.7.7
- Ubuntu 18.04
- RStudio 1.3.1073

**Comment by holnburger** [comment]
> Any idea what might the next step be here?

Had the same error as you @stragu . I installed the newest version of `stringi` as @wush978 suggested and installation finished successfully without the error message containing the .tar.gz error.

Nevertheless a new error appeared.
```
Selenium message:session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 86.0.4240.111 with binary path /usr/bin/google-chrome
```

I'll try to fix that one and keep you updated.

**Comment by alvinndo** [comment]
Hi team, any updates on how to fix the issue with the zip or tar file?

> Error in (function (platform, file, processed, chmod)  : 
  /home/rstudio/.local/share/binman_geckodriver/linux64/0.28.0/geckodriver-v0.28.0-linux64.tar.gz.asc does not appear to be a zip or tar file.

**Comment by MaximumV** [comment]
> Hi team, any updates on how to fix the issue with the zip or tar file?
> 
> > Error in (function (platform, file, processed, chmod)  :
> > /home/rstudio/.local/share/binman_geckodriver/linux64/0.28.0/geckodriver-v0.28.0-linux64.tar.gz.asc does not appear to be a zip or tar file.
> 
> I'm currently running RStudio through AWS EC2 server so my issue may have a different turn..

Hi! have you succeded? pls share your experience
