### ISSUE TITLE
problem: $clickElement() without "click"

### ISSUE THREAD

**Issue by mcps** [ropensci/RSelenium#20]
Dear John,

During the first test with RSelenium appeared one problem. Perhaps you could help me in finding the solution?

Description of the problem:

I went through all the steps, which are listed at http://rpubs.com/johndharrison/12843. There were no problems until to the step with “Sending mouse events to elements”.

What I did in RStudio was the following:

remDr$navigate("http://www.google.com/ncr")
webElem <- remDr$findElement(using = "xpath", "//*/input[@id = 'gbqfq']")
webElem$sendKeysToElement(list("R Cran", key = "enter"))

webElems <- remDr$findElements(using = 'css selector', "li.g h3.r")
resHeaders <- unlist(lapply(webElems, function(x){x$getElementText()}))
resHeaders

webElem <- webElems[[which(resHeaders == "The Comprehensive R Archive Network")]]
webElem$clickElement()

After “webElem$clickElement()” there was unfortunately no „click“. I tried different possibilities, but i couldn´t find the solution.

I work with
- Mac OS 10.8.5,
- Firefox 29.0.1,
- RStudio 0.97.320,
- R 3.1.0
- Terminal 2.3 (309)

I would be very pleased to receive your answer.

Kind regards,

**Comment by ponnet** [comment]
Hi everyone - have the same problem on Windows and Chrome combination:
click() or clickElement() do absolutely nothing (on multiple pages)

What worked is:
sendKeysToElement(list(key="enter"))


Please advise!

**Comment by WaasThissen** [comment]
I had the same problem with a Mac and Chrome combination.

The solution by @ponnet worked great for me. Thanks!!
