### ISSUE TITLE
Overwriting registered S3 method

### ISSUE THREAD

**Issue by GeraldCNelson** [ropensci/RSelenium#204]
Since the release of R version 3.6, I have started seeing these kinds of messages in several packages I use 
```
library(RSelenium)
Registered S3 method overwritten by 'openssl':
  method      from
  print.bytes Rcpp
```

For another package I was told that "these packages don't prefix their class with the package name (e.g. "Rcpp_bytes") so there are collisions when they register methods for third party generics like print().

Is this something you could do to make these messages go away?  Would there be any chance either of you could rename your class to use your package name as a prefix? It probably makes sense to do this renaming in the package with the fewest reverse dependencies, to minimise breakages.

**Comment by juyeongkim** [comment]
https://github.com/jeroen/openssl/issues/70
