### ISSUE TITLE
$mouseMoveToLocation without "move"

### ISSUE THREAD

**Issue by mcps** [ropensci/RSelenium#21]
Dear John,

During the first test with RSelenium appeared one problem due to $mouseMoveToLocation. Perhaps you could help me in finding the solution?

Description of the problem:

I went through following the steps in RStudio:

remDr$navigate("http://www.r-project.org") 
  remDr$switchToFrame("banner")
  webElem <- remDr$findElement("partial link text", "download R")
  webElem$getElementText()
  loc <- webElem$getElementLocation()
  loc[c('x','y')] ####################### everything okay so far
  remDr$mouseMoveToLocation(webElement = webElem) # error

details of the error:
Error:   Summary: InvalidElementState

Detail: An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element).

```
class: org.openqa.selenium.InvalidElementStateException
```

I work with

Mac OS 10.8.5,
Firefox 29.0.1,
RStudio 0.97.320,
R 3.1.0

I would be very pleased to receive your answer.

Kind regards,

Pawel

**Comment by jsta** [comment]
I am getting this error yet:

> remDr$sessionInfo$nativeEvents
[1] TRUE

The solution indeed was to use chrome.
