### ISSUE TITLE
RSelenium is archived on CRAN and not available anymore

### ISSUE THREAD

**Issue by khufkens** [ropensci/RSelenium#227]
RSelenium is unnecessarily archived on CRAN, which causes delisting of other packages further down stream. Simple resubmission should suffice, as this is a `wdman` dependency issue. Sadly, CRAN (Brian Ripley?) was probably too quick to jump the gun on archiving `wdman` I assume.

**Comment by jeroen** [comment]
The maintainer is working on it, should be submitted soon.

**Comment by khufkens** [comment]
Thanks. Didn't want to put any additional pressure, just wanted to put out a reminder because things didn't get reinstated.

They were just a bit to quick to make things defunct down the chain I think, without a fallback to leave things be if need be.

**Comment by jeroen** [comment]
Yeah the CRAN maintainers don't have much patience or grace for package authors unfortunately. But hopefully everything will be back online very soon.

**Comment by dmurdoch** [comment]
It has been online since Feb 3; this issue should be closed.
