### ISSUE TITLE
R package development with vignette using RSelenium: recommendation for CRAN to not build vignette?

### ISSUE THREAD

**Issue by vinhdizzo** [ropensci/RSelenium#253]
Hi,

I am writing some vignettes on RSelenium for a package I am developing.  The vignette leverages docker and Selenium to webscrape a particular site.

I do plan to submit the package to CRAN soon.  What is the recommended way to write a vignette and ask CRAN to not test build the vignette on their servers as I'm sure it will fail?  I'm asking here because I believe you have experience when writing vignettes for RSelenium, and RSelenium has been submitted to CRAN.

Thank you for your assistance!

**Comment by juyeongkim** [comment]
https://ropensci.org/blog/2019/12/08/precompute-vignettes/
