### ISSUE TITLE
Browsers

### ISSUE THREAD

**Issue by msgoussi** [ropensci/RSelenium#257]
Hi...
I am wondering why Rselenium is not accepting to use Brave or MS Edge since i am getting this error

Error in match.arg(browser) : 
'arg' should be one of “chrome”, “firefox”, “phantomjs”, “internet explorer”

**Comment by ggSamoora** [comment]
I don't think it would work in Edge nor Brave. I suggest you use Google Chrome. Here is some code to set you up: 

```
library(RSelenium)

remDr <- rsDriver(browser = 'chrome',
                  chromever = '97.0.4692.71')
# to check your chrome version, open Chrome and in the URL box type
#   chrome://version
# your version type will be at the top of the page
# then go to R, and in the console type:
#   binman::list_versions('chromedriver')
# it will give you a list of versions, pick the one that has the same first 2 digits as yours

# access the client
remDr <- remDr$client
```

I made a full tutorial on using RSelenium. You can find the YouTube video [here](https://www.youtube.com/watch?v=U1BrIPmhx10&t=1277s&ab_channel=SamerHijjazi).

**Comment by msgoussi** [comment]
each browser has its advantages and disadvantages.
