### ISSUE TITLE
Impending CRAN archival

### ISSUE THREAD

**Issue by jeffreyhanson** [ropensci/RSelenium#260]
Hi,

Thank you very much for all your work on developing and maintaining the Rselenium package! I maintain a package that depends on RSelenium and I recived an email from CRAN stating that Rselenium will be archived on 2022-09-03. I haved copied in the full email below for reference. Please let me know if there's anything I can do to help resolve this?

------------------

Dear maintainers,

This concerns the CRAN packages

  IRexamples LIHKGr RSelenium carbonate gesisdata nser parsel pewdata
  ropercenter sgat shadowr snotelr wdpar

maintained by one of you:

  Frederick Solt <XXXXX>: gesisdata pewdata
        ropercenter
  Jeffrey O Hanson <XXXXX>: wdpar
  Jonathan Sidi <XXXXX>: carbonate
  Ju Yeong Kim <jXXXXX>: RSelenium
  Justin Chun-ting Ho <XXXXX>: LIHKGr
  Koen Hufkens <XXXXX>: snotelr
  Matias Poullain <XXXXX>: sgat
  Nandan Patil <XXXXX>: nser
  Ricardo Landolt <XXXXX>: shadowr
  Till Tietz <XXXXX>: parsel
  Vinh Nguyen <XXXXX>: IRexamples

We have asked for an update fixing the check problems shown at
  <https://cran.r-project.org/web/checks/check_results_RSelenium.html>
with no update from the maintainer thus far.

Thus, package RSelenium is now scheduled for archival on 2022-09-03,
and archiving this will necessitate also archiving its CRAN strong
reverse dependencies.

Please negotiate the necessary actions.

The CRAN Team

**Comment by jeffreyhanson** [comment]
Upon further inspection, it seems that some of the vignettes are failing to build under the ALTAS environment. If it would be helpful, I would be happy to submit a PR that programmatically disables evaluation of R code in vignettes when run as part of package checks (based on https://stackoverflow.com/a/46482580/3483791). I have used this method in vignettes that are computationally heavy, and would not normally pass CRAN package checks (e.g., https://github.com/prioritizr/prioritizr/blob/master/vignettes/calibrating_trade-offs_tutorial.Rmd).

**Comment by jeffreyhanson** [comment]
Just thought I'd tag @juyeongkim in this issue, in case that helps.

**Comment by yonicd** [comment]
cc @maelle

**Comment by maelle** [comment]
I emailed the maintainer, thank you!

**Comment by FultonCountyStrategyOffice** [comment]
@jeffreyhanson @maelle @maelle Hi, I just though Fulton County Government should throw out hat in the ring.  We use RSelenium as a webscraper of last resort to make sure people don't break the law.   The dependency of the justice system on Selenium is important enough that I am speaking openly about it, and I will try to personally reach out to @johndharrison and @juyeongkim personally ourselves to see if anything can be done.   Then I will reach out to CRAN themselves to see if the 09/03 can be delayed. 

Please keep us updated if you hear anything back from the maintainer as we are willing to pursue.

**Comment by juyeongkim** [comment]
Hi all, I am aware of this issue and will address it and resubmit to CRAN soon.

I am looking for a new maintainer. Please comment on #261 if you are interested.

**Comment by jeffreyhanson** [comment]
I'm sorry @juyeongkim, I don't the bandwidth at the moment to take on maintainer duties for another package. I just saw that a new version had been released on CRAN - thank you very much! I really appreciate it.
