### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by juyeongkim** [ropensci/RSelenium#261]
Hello all!

I am looking for a new maintainer(s) for RSelenium, wdman, and binman packages.

If you're interested, please comment in the issue.

For more info, see
- [rOpenSci guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [rOpenSci Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

**Comment by maelle** [comment]
Relevant issue for a new maintainer: https://github.com/ropensci/RSelenium/issues/259 by @diemol

**Comment by maelle** [comment]
@ropensci/admin

**Comment by pachadotdev** [comment]
hi, i'm using both for my thesis, so happy to

**Comment by noamross** [comment]
Thanks @pachadotdev for volunteering, but we're still looking for a maintainer as he already maintains multiple RO packages and we aim to spread this work around!

**Comment by pachadotdev** [comment]
> 

hi! still available if needed, I'll be using RSelenium intensively for the next 6 months

**Comment by bedantaguru** [comment]
I am ready to help

**Comment by jonathanvoelkle** [comment]
Hi @juyeongkim, 

I can take over maintaining this lovely R package, I use (R)Selenium mostly for webscraping, so this is critical infrastructure for me and my team (had a brief chat with maelle before).

**Comment by bedantaguru** [comment]
@jonathanvoelkle 
+1 me

**Comment by maelle** [comment]
@jonathanvoelkle @bedantaguru could you please update the DESCRIPTION file with the new authors including new maintainer? Thank you!
