### ISSUE TITLE
Chrome updated to 116 and driver works for 114.

### ISSUE THREAD

**Issue by dietrichson** [ropensci/RSelenium#281]
Does anyone know a workaround for this? 

### Operating System
Mac OS X 12.6.7 x86_64

### Selenium Server version (selenium-server-standalone-3.0.1.jar etc.)

Standalone-4.0.0-alpha2-jar 

binman_chromedriver/mac64/114.0.5735.90/chromedriver'

### Browser version (firefox 50.1.0, chrome 54.0.2840.100 (64-bit) etc.)
Chrome 116.0.5845.96 

### Expected behaviour
Open browser
### Actual behaviour
Stop with the error message pasted below.
### Steps to reproduce the behaviour

library(RSelenium)
library(wdman)
selenium(retcommand = TRUE)
#selenium()

```
cDrv <- chrome()
remDr <- remoteDriver(
  remoteServerAddr = "localhost",
  port = 4567L,
  browserName = "chrome"
)
remDr$open()

```
Selenium message:session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.96 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
  (Driver info: chromedriver=114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052}),platform=Mac OS X 12.6.7 x86_64)

Error: 	 Summary: SessionNotCreatedException
 	 Detail: A new session could not be created.
	 Further Details: run errorDetails method
In addition: Warning messages:
1: In class(object) <- "environment" :
  Setting class(x) to "environment" sets attribute to NULL; result will no longer be an S4 object
2: In class(object) <- "environment" :
  Setting class(x) to "environment" sets attribute to NULL; result will no longer be an S4 object

**Comment by oobd** [comment]
@dietrichson i made a comment with workaround in the wdman repo and i believe there was a workaround for mac as well

[wdman issue](https://github.com/ropensci/wdman/issues/34#issuecomment-1691678436)

**Comment by maelle** [comment]
@jonathanvoelkle are you able to help?

**Comment by dietrichson** [comment]
@oobd the workaround works. Closing issue.
