### ISSUE TITLE
PhantomJS not working properly

### ISSUE THREAD

**Issue by alexanderchernyakov** [ropensci/RSelenium#30]
require(RSelenium)
#Loading required package: RSelenium
#Loading required package: RCurl
#Loading required package: bitops
#Loading required package: RJSONIO
#Loading required package: XML

psPath <- "C:/Users/home/Desktop/phantomjs-1.9.8-windows/phantomjs.exe"
RSelenium::startServer()
remDr <- remoteDriver(browserName = "phantomjs", extraCapabilities = list(phantomjs.binary.path = psPath))
remDr$open()
#[1] "Connecting to remote server"
#Error:   Summary: UnknownError
#Detail: An unknown server-side error occurred while processing the command.
#class: java.lang.ClassNotFoundException

**Comment by johndharrison** [comment]
This issue is fixed as of phantomjs 2.0 and selenium server 2.45.0

```
library(RSelenium)
RSelenium::startServer()
remDr <- remoteDriver(browserName = "phantomjs")
remDr$open()

> remDr$getStatus()$build
$version
[1] "2.45.0"

$revision
[1] "5017cb8"

$time
[1] "2015-02-26 23:59:50"

> remDr$sessionInfo[c("version", "driverVersion")]
$version
[1] "2.0.0"

$driverVersion
[1] "1.2.0"
```
