### ISSUE TITLE
checkForServer issuse

### ISSUE THREAD

**Issue by funnng** [ropensci/RSelenium#36]
As the selenium server download url has moved to http://selenium-release.storage.googleapis.com/index.html, `checkForServer` won't works as before.

**Comment by johndharrison** [comment]
Hi funnng,

What issues are you encountering?  The current version of `checkForServer` is referencing the url you suggest https://github.com/ropensci/RSelenium/blob/master/R/util.R#L17

John

**Comment by funnng** [comment]
forget it, it's my network problem.
