### ISSUE TITLE
Programmatically stopping selenium

### ISSUE THREAD

**Issue by cpsievert** [ropensci/RSelenium#37]
It'd be nice to have a `stopServer()` function to programmatically stop selenium from running in the background. I'm guessing this doesn't exist already because there is no nice cross-platform solution? Borrowing ideas from `RSelenium::phantom()`, I have a solution for Mac OS X, but I have no idea how to attack this on Windows...

```r
RSelenium::startServer()
# this function probably only works on Darwin
stopServer <- function() {
  x <- system("ps -Ao\"pid,args\"", intern = TRUE)
  cmds <- sub("^\\s*(\\d+)(.*)", "\\1,\\2", x)
  y <- read.csv(text = cmds[-1], stringsAsFactors = FALSE, header = F)
  pid <- y[grepl("selenium-server-standalone.jar", y[,2]), 1]
  tools::pskill(pid)
}
stopServer()
```

**Comment by johndharrison** [comment]
Hi Carson

There is a closeServer method in the remoteDriver class that will close down the Selenium Server.
You will need to initiate a remoteDriver however:

```
RSelenium::startServer()
remDr <- remoteDriver()
remDr$closeServer()
```

**Comment by cpsievert** [comment]
Ah, yes. Thanks!
