### ISSUE TITLE
Latest update of OS X Yosemite (V 10.10.2)

### ISSUE THREAD

**Issue by CiocZH** [ropensci/RSelenium#39]
Hi,
Late last month RSelenium stopped working for me. This coincides with an upgrade of OS X Yosemite I  performed on the same day as it stopped working. The generic error message generated by R doesn't help in identifying the error and after a week of sweeping the internet forums for a solution, I still couldn't find it. The RScript can't get past the "remDr$open" command.

In case this is an issue for other Mac users, I'm looking forward to a solution.

Best
C.D.

**Comment by johndharrison** [comment]
Hi C.D.

I do not currently have access to OS X Yosemite so unfortunately I cannot investigate this issue.

**Comment by funnng** [comment]
i got the same issue in windows 7
```
remDr$open(silent=T)
Undefined error in RCurl call.
Error in queryRD(paste0(serverURL, "/session"), "POST", qdata = toJSON(serverOpts)) : 
```
