### ISSUE TITLE
RSelenium executing script gives UnknownError

### ISSUE THREAD

**Issue by nilsmackay** [ropensci/RSelenium#40]
Hi,

I would appreciate some help with RSelenium.
I've been trying to scrape data from squawka.com, following this example found on stackoverflow:
http://stackoverflow.com/questions/22121006/how-to-scrape-this-squawka-page 

This however does not produce the wanted results for me. When trying to execute the code:

```
library(RSelenium)
checkForServer(update = TRUE)
startServer()

remDr <- remoteDriver()
remDr$open()
remDr$setImplicitWaitTimeout(3000)
remDr$navigate("http://eredivisie.squawka.com/feyenoord-vs-ajax/02-03-2014/dutch-eredivisie/matches")
```

Everything works fine. Firefox is opened and directed towards the URL. However when I try to execute the line:
```
squawkData <- remDr$executeScript("return XMLSerializer().serializeToString(squawkaDp.xml);", list())
```

It produces the following error:
```
Error: 	 Summary: UnknownError
 	 Detail: An unknown server-side error occurred while processing the command.
 	 class: org.openqa.selenium.WebDriverException
```
If looked this error up, and noticed most people encounter this error when trying the remDr$open() command, which wasn't really applicable to this situation. If searched the internet to find out what was going wrong but with no success.

Thanks in advance for any help/advice.

**Comment by johndharrison** [comment]
Hi @nilsmackay 

try replacing 

```
squawkData <- remDr$executeScript("return XMLSerializer().serializeToString(squawkaDp.xml);", list())
```

with

```
squawkData <- remDr$executeScript("return new XMLSerializer().serializeToString(squawkaDp.xml);", list())
```

**Comment by nilsmackay** [comment]
Ha wow I totally missed that. I'm pretty new to this, probably need to freshen up my JavaScript a bit...
Thanks a lot for your help!!

**Comment by johndharrison** [comment]
The old code used to work with firefox but not with the current version of firefox. Also calling `new XMLSerializer()` should be compatible with Google Chrome now.
