### ISSUE TITLE
Suppress Logs to R Console

### ISSUE THREAD

**Issue by masterperez** [ropensci/RSelenium#43]
Hello!

First off: Fantastic package.

Secondly:  I would like to suppress all logs (or learn how to selectively block WARN logs) coming from the selenium server into the R console.  They just seem to be a bit verbose.  

Example console outputs that I would like to learn how to remove: 
   "20:48:18.988 INFO - Executing [...]" 
  "20:48:19.970 WARN - Exception thrown [...]" 

I am guessing this can be done by passing the appropriate keys via the 'extraCapabilities' argument when setting up a remoteDriver() but I cannot figure out what those keys should be!

Any help would be greatly appreciated.

-Marc

**Comment by johndharrison** [comment]
Logs are handled with `wdman` package and related `wdman::phantomjs` and `RSelenium::rsDriver` functions.
