### ISSUE TITLE
Getting an error when trying to open a remote server

### ISSUE THREAD

**Issue by kendonB** [ropensci/RSelenium#44]
I run the following code:

    library(RSelenium)
    appURL <- ("www.google.com")
    RSelenium::checkForServer()
    RSelenium::startServer()
    remDr <- RSelenium::remoteDriver()
    remDr$open()

And I get this error:

    [1] "Connecting to remote server"
    Error: 	 Summary: UnknownError
     	     Detail: An unknown server-side error occurred while processing the command.
 	         class: org.openqa.selenium.firefox.NotConnectedException

I am running R 3.1.3, RSelenium 1.3.6, and Firefox 37.0.2

**Comment by kendonB** [comment]
I tried downgrading Firefox and it now seems to be working. I'm now using Firefox 34.0.

**Comment by johndharrison** [comment]
Hi @kendonB 

Can you run:

```
> remDr$getStatus()$build
$version
[1] "2.45.0"

$revision
[1] "5017cb8"

$time
[1] "2015-02-26 23:59:50"
```

You can run this without having a browser open. It will tell you the current Selenium Server version running. 2.45.0 is the most version. You can update your selenium server by running:
```
RSelenium::checkForServer(update = TRUE)
```
Selenium Server 2.45.0 should drive Firefox 37.0.2.

Support for Firefox is the latest release, the previous release, the latest ESR release and the previous ESR release. For example Selenium 2.40.0 (released on Feb 19, 2014) supports Firefox 27, 26, 24, 17. Details of the current ESR can be found at https://www.mozilla.org/en-US/firefox/organizations/faq/. The current ESR is firefox 31. In addition the most recent Selenium Server may drive other versions of Firefox but this is not guaranteed.

There can occasionally be a couple of days lag between a new Selenium Server and a new release of Firefox.

**Comment by kendonB** [comment]
Working fine now!
