### ISSUE TITLE
newWindow or newTab method?

### ISSUE THREAD

**Issue by tdhock** [ropensci/RSelenium#45]
I would like to open a new browser tab or window, and then close it.

I see that the remoteDriver class has a closeWindow method https://github.com/ropensci/RSelenium/blob/master/R/remoteDriver.R#L339 but I can't find a newWindow method, or even better a newTab method. Could this be added?

Would adding a new browser tab be portable across phantomjs and firefox?

**Comment by johndharrison** [comment]
Hi Toby,

I havent ran it on the various browsers but would

```
remDr$executeScript('window.open("", "windowName", "height=200,width=200");')
```

have the desired effect. That should open a new window. The windows can be accessed with methods `switchToWindow`, `getWindowHandles` etc. The notion of a tab doesn't really exist. There are no tabs in Selenium only windows. Most browsers implement new tabs as new windows behind the scenes I seem to recall.

**Comment by tdhock** [comment]
Thanks for the quick response!

That helps to know that tabs don't really exist in Selenium.

In fact, I just wanted to navigate to a new tab in order to send a visibilitychange event to my browser window. https://developer.mozilla.org/en-US/docs/Web/Events/visibilitychange

Would there be another way to simulate sending a visibilitychange event? I would like to first send one with document.visibilityState == "hidden" and then another one with document.visibilityState == "visible"

**Comment by johndharrison** [comment]
Hi Toby,

In Firefox if the new tab exists then you can do something like the following to switch between tabs
```
library(RSelenium)
RSelenium::startServer()
remDr <- remoteDriver()
remDr$open()
remDr$navigate("")
webElem <- remDr$findElement("css", "body")
webElem$sendKeysToElement(list(key = "control", "t"))
# switch back to first tab
webElem$sendKeysToElement(list(key = "control", key = "tab"))
```
`phantomjs` wouldnt have tabs and everything would open in a new window. You can start firefox with a profile which prohibits new tabs and only opens new windows:

```
# 1: current tab; 2:new window; 3:new tab; 
fprof <- makeFirefoxProfile(list(browser.link.open_newwindow = 2L))
remDr <- remoteDriver(extraCapabilities = fprof)
remDr$open()

```

I cant think of a way of sending a visibility change event. Obviously minimising the browser would do this but Selenium doesn't have this function.

**Comment by tdhock** [comment]
If Selenium doesn't have such a function then I guess this is not a bug in your RSelenium code per se. Should I forward this issue to the Selenium devs?

**Comment by lnalborczyk** [comment]
Hi, sorry to re-up this issue, but I am a novice to Selenium (and to RSelenium) and I can not open a new tab on mac OSX using `webElem$sendKeysToElement(list(key = "control", "t"))`. My guess is that because on mac you open a new tab with command+t rather than control+t but from looking at https://github.com/ropensci/RSelenium/blob/master/R/selKeys-data.R I do not think there is a key mapped to the apple "cmd" key... am I wrong? Is there a workaround?

**Comment by dnlbrky** [comment]
@lnalborczyk I believe the macOS ⌘ command key is the last one in the list from the file you referenced (`command_meta = "\uE03D"`).

I am able to open and close tabs using these functions:

```r
## Open a new tab
client_tab_open <- function(client, switch=TRUE) {
  
  ## Get the current list of windows (tabs?)
  w_before <- unlist(client$getWindowHandles())
  
  ## Open a new tab
  client$executeScript("window.open('', '_blank').focus();")
  
  ## Get the updated list of windows
  w_after <- unlist(client$getWindowHandles())
  
  ## Identify the first new window
  w_new <- setdiff(w_after, w_before)[1]

  ## Switch to it
  if(switch) client$switchToWindow(w_new)
  
  return(w_new)
}

## Close a tab
client_tab_close <- function(client, id_switch, id_close) {
  
  ## Current window (tab?)
  w <- unlist(client$getCurrentWindowHandle())
  
  ## If id_close isn't specified, close the current window
  if(!hasArg(id_close)) id_close <- w
  
  ## If the current window isn't the one to close, switch to it
  if(w != id_close) client$switchToWindow(id_close)
  
  ## Close the window
  client$closeWindow()
  
  ## If an id hasn't been specified, get the last one that's currently open
  if(!hasArg(id_switch)) id_switch <- tail(unlist(client$getWindowHandles()), 1)
  
  ## The ol' switcheroo
  client$switchToWindow(id_switch)
  
  return(id_switch)
}
```

Example:

```r
## Load RSelenium
pacman::p_load(RSelenium)

## Create a Firefox driver
ff_d <- rsDriver(browser="firefox")

## Get the Firefox client
ff_c <- ff_d$client

## Open sesame
client_tab_open(ff_c)

## Close it
client_tab_close(ff_c)
```
