### ISSUE TITLE
Unknown IO error2: failed to load external entity in checkForServer()

### ISSUE THREAD

**Issue by caijun** [ropensci/RSelenium#50]
I am working in RStudio with following session infomation

```
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.0
```

When running `checkForServer()`, I got the following error

```
> library("RSelenium")
Loading required package: RCurl
Loading required package: bitops
Loading required package: RJSONIO
Loading required package: XML
> checkForServer()
Unknown IO errorfailed to load external entity "http://selenium-release.storage.googleapis.com"
Error: 1: Unknown IO error2: failed to load external entity "http://selenium-release.storage.googleapis.com"
``` 

I google the error and find that it's probably caused by `libxml2`, on which the `xmlTreeParse()`, `htmlTreeParse()` and `xmlEventParse()` functions are built.

**Comment by caijun** [comment]
This is due to a networking problem as it's difficult to access to websites of google in Mainland China. After setting an http_proxy for R by `Sys.setenv(http_proxy = "http://localhost:8123")`, `checkForServer()` works well.

**Comment by johndharrison** [comment]
Thanks Tony glad you sorted it out.
