### ISSUE TITLE
Bug in checkForServer function

### ISSUE THREAD

**Issue by josealber84** [ropensci/RSelenium#52]
I think there is a bug in the source code of the "checkForServer" function:

*selXML <- xmlParse(paste0(selURL), "/?delimiter=")*

should be:

*selXML <- xmlParse(paste0(selURL, "/?delimiter="))*

Thank you for the excelent job!

**Comment by johndharrison** [comment]
Hi @josealber84 

Thanks yes that looks like an ommission. Would you like to submit a pull request and I'll look to get it fixed or I can fix it.

Thanks

John

**Comment by josealber84** [comment]
Hi John,

I don't usually use GitHub, so I think it will be faster if you fix it.

Thanks again.
