### ISSUE TITLE
Do we need selenium server?

### ISSUE THREAD

**Issue by izahn** [ropensci/RSelenium#53]
This is a n00b question, but do we actually need the java server? The python package[1] says it is not needed unless using the old API or driving a remote browser. It would be nice to drop this dependency, especially because the selenium binary sometimes goes crazing hogging cpu and network on my system.

[1] https://pypi.python.org/pypi/selenium

**Comment by johndharrison** [comment]
Hi Ista,

Yes you currently need to connect to a "server". RSelenium implements the JSON wire protocol API underlying selenium. It needs to connect to a server implementing this API. The standalone selenium server is one such option. phantomJS also implements the API. The python package is an official package which incorporates the server. https://github.com/LluisRamon/relenium provides bindings for Selenium using the java official package. It currently supports selenium 2.41 and may be useful depending on your needs. Alternatively https://github.com/cpsievert/rdom from @cpsievert provides an easy interface to phantomJS and may be useful to you.

Best Regards

John
