### ISSUE TITLE
httr?

### ISSUE THREAD

**Issue by Ironholds** [ropensci/RSelenium#62]
I'm sure this has been raised and I've simply missed it, but: is there a reason not to move to the httr/curl stack?

(If it's "that's a lot of code we haven't written yet", totally understandable!)

**Comment by johndharrison** [comment]
HI Oliver,

When RSelenium was first developed httr/curl wasn't a option. There shouldn't be any great hurdles to using one or the other. "that's a lot of code we haven't written yet" is certainly part of it as well as testing that code etc. We do accept pull request thou hehe ;)

John

**Comment by Ironholds** [comment]
Awesome; I'll start noodling around! :D

**Comment by johndharrison** [comment]
Hi @Ironholds there is an alternative R driver for Selenium which implements the w3c webdriver specification built on the httr/xml2/curl/magrittr stack. Beta version is at
https://github.com/johndharrison/seleniumPipes

**Comment by Ironholds** [comment]
Cool!

**Comment by johndharrison** [comment]
On CRAN now:

https://cran.r-project.org/web/packages/seleniumPipes/index.html

Vignette on basic operation:

http://rpubs.com/johndharrison/seleniumPipes-basic
