### ISSUE TITLE
do not write logs by default to installed package directory

### ISSUE THREAD

**Issue by dtenenba** [ropensci/RSelenium#66]
Hi,

If packages are installed by an administrative user and then R is run by a non-administrative server (a common scenario, even on non-shared machines) then running `startServer()` without any arguments will fail to write the log file to the directory where RSelenium is installed.

Of course, you can work around that with something like:

```
RSelenium::startServer(args=paste("-log", tempfile()), log=FALSE)
```

However, it's very bad to have the _default_ behavior be writing to the installed package directory. The reason above (permissions) is only one reason. It's also a bad place to write a log file that you might want to reference again later, because it will be removed the next time the RSelenium package is reinstalled, updated, or removed. 

I work in the Bioconductor group and we consider this a bad practice. If a package that's submitted to us has this behavior, we ask the author to change it before accepting the package.

I'm not sure exactly what the solution should be....but I'm very sure that the default behavior should not be to the installed package directory.

Perhaps the `log` argument should be NULL by default, meaning don't log, and if set to a character value, use that filename as the log. Or you could log by default to `tempfile("selenium.log")` which will write to a file that you should have permission to write to, in a directory that will be removed when the R session ends.

Thanks.

@wikiselev @b-long

**Comment by b-long** [comment]
:+1:

**Comment by dtenenba** [comment]
It also looks like checkForServer() downloads the selenium jar by default to the installed package directory which is going to cause the same problem if that directory is not writable by the user running R. 

Would it make the package too big to simply include the jar in the package?
