### ISSUE TITLE
no way to stop selenium server

### ISSUE THREAD

**Issue by dtenenba** [ropensci/RSelenium#67]
Hi,
RSelenium provides `startServer()` but does not provide `stopServer()`. A Bioconductor package depends on RSelenium and calls `startServer()` but it hangs our automated build on WIndows, which tries to clean up by deleting the .Rcheck files left behind by R CMD check, but can't because the java (selenium) process has a handle holding onto those files.

Can you provide a function to stop the selenium server (in a cross-platform way) as well? It might also be good if the process ID of the server were made available.

Thanks.

@b-long

**Comment by b-long** [comment]
Seems like an important issue.  Has anyone found a workaround?

cc/ @englianhu @suensummit @RobertMyles @olivmx @thomasKuilman

**Comment by b-long** [comment]
Alternatively, can someone from @ropensci comment on this?

**Comment by dtenenba** [comment]
I've written a little function to kill the selenium server. It's called `stopSeleniumServer()` and in the function where the selenium server is started, I've added:

    on.exit(stopSeleniumServer()) 

but you could put that anywhere that the code will go before exiting the package.

Here is the function. It's not perfect (I think it might fail if there is more than one matching process on windows) but should be good for most cases:

```
stopSeleniumServer <- function()
{
    if (.Platform$OS.type == "windows")
    {
        procs <- system2("wmic",
            "path win32_process get Caption,Processid,Commandline",
            stdout=TRUE, stderr=NULL)
        idx <- grep("selenium-server-standalone.jar", procs)
        if (!length(idx)) # selenium not running?
            return()
        proc <- procs[idx]
        proc <- trimws(proc)
        segs <- strsplit(proc, " ", TRUE)[[1]]
        pid <- segs[length(segs)]
        system2("taskkill", c("/pid", pid, "/f"), stdout=NULL, stderr=NULL)
    } else {
        # Unfortunately field width specifiers do not work on Mac
        # so we need two commands to get pid and command non-truncated.
        pidcmd <- system2("ps", "wwaxo pid,command", stdout=TRUE, stderr=NULL)
        pidusr <- system2("ps", "wwaxo pid,user", stdout=TRUE, stderr=NULL)
        pidusr <- trimws(pidusr)
        whoami <- system2("whoami", stdout=TRUE, stderr=NULL)
        pididx <- grep(paste0(whoami, "$"), pidusr)
        pidusr <- pidusr[pididx]
        tmp <- strsplit(pidusr, " ")
        pids <- unlist(lapply(tmp, function(x) x[1]))
        procs_idx <- grep("selenium-server-standalone.jar", pidcmd)
        for (proc in pidcmd[procs_idx])
        {
            pid <- strsplit(proc, " ")[[1]][1]
            if (pid %in% pids) 
            {
                system2("kill", c("-9", pid))
            }
        }
    }
}
```

@b-long arguably the problem is on our side and the Bioconductor build system should make sure that it kills any processes started by R processes that it starts, but I don't think anyone wants these orphaned processes left around after they are done using RSelenium. 

@ropensci - A better solution would probably be for RSelenium to keep track of the PID of the selenium server when it is started, and then `stopSeleniumServer()` can simply kill the process with that pid.

**Comment by johndharrison** [comment]
Currently the selenium server can be stopped using the `closeServer` method in the Remote Driver class. For example `remDr$closeServer()`. I think as noted above it would be useful to capture the process id if `startServer` is used to instantiate an instance of Selenium Server.

**Comment by johndharrison** [comment]
There is now a vignette on running RSelenium and Docker which should reduce platform specific issues
http://rpubs.com/johndharrison/RSelenium-Docker

**Comment by b-long** [comment]
👍

**Comment by mkronborg** [comment]
Hi John,
I am having a similar issue, however, running remDr$closeServer() produces the following result:

`"Unknown Command - {\"headers\":{\"Accept\":\"application/json, text/xml, application/xml, */*\",\"Accept-Encoding\":\"gzip, deflate\",\"Host\":\"localhost:4443\",\"User-Agent\":\"libcurl/7.63.0 r-curl/3.3 httr/1.4.0\"},\"httpVersion\":\"1.1\",\"method\":\"GET\",\"url\":\"/selenium-server/driver/?cmd=shutDownSeleniumServer\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"cmd=shutDownSeleniumServer\",\"file\":\"\",\"directory\":\"/selenium-server/driver/\",\"path\":\"/selenium-server/driver/\",\"relative\":\"/selenium-server/driver/?cmd=shutDownSeleniumServer\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/selenium-server/driver/?cmd=shutDownSeleniumServer\",\"queryKey\":{\"cmd\":\"shutDownSeleniumServer\"},\"chunks\":[\"selenium-server\",\"driver\",\"?cmd=shutDownSeleniumServer\"]}}"`
