### ISSUE TITLE
Phantom JS hangs with more than two elements lapply

### ISSUE THREAD

**Issue by sobradob** [ropensci/RSelenium#73]
I have a line of code that works well when using Firefox as a browser but fails when using phantomjs. The example is from the [page likes tab:](https://www.facebook.com/ads/audience_insights/interests?act=71238683&age=18-&country=US) 

`unlist(lapply(remDr$findElements(using = 'css selector', "._32n0"), function(x){x$getElementText()}))`

Upon closer inspection it fails when there are more than two elements. The issue has been discussed before on [Stackoverflow](http://stackoverflow.com/questions/30889645/in-r-phantomjs-ran-with-rselenium-hangs-after-several-iterations). 
.

**Comment by johndharrison** [comment]
This issue should be fixed now.
