### ISSUE TITLE
java.lang.IllegalStateException error

### ISSUE THREAD

**Issue by sjorsvanheuveln** [ropensci/RSelenium#74]
I'm operating a daemon that executes an R script on mac osx. It works fine when I run it with a firefox browser. However, the phantomjs headless browser is showing some problems:

```
[1] "Connecting to remote server"
Error :      Summary: UnknownError
     Detail: An unknown server-side error occurred while processing the command.
     class: java.lang.IllegalStateException
```

It is also throwing this error:

```
[ERROR - 2016-04-27T14:42:01.509Z] GhostDriver - main.fail - {"line":85,"sourceURL":"phantomjs://code/main.js","stack":"global code@phantomjs://code/main.js:85:56"}

  phantomjs://platform/console++.js:263 in error
[ERROR - 2016-04-27T14:42:01.650Z] GhostDriver - main.fail - {"line":85,"sourceURL":"phantomjs://code/main.js","stack":"global code@phantomjs://code/main.js:85:56"}

  phantomjs://platform/console++.js:263 in error
```

The way I installed phantomjs is by downloading the zip from phantomjs.org and then putting the binary in /opt/local/bin.

When I check both in terminal and in R, both environments are pointing to the same binary :

```
system('which phantomjs')
/opt/local/bin/phantomjs

Sys.which('phantomjs')
"/opt/local/bin/phantomjs"
```

Could someone please help me with solving this issue. I've spent already so much time in fixing it, but I can't get my head around the problem. Thanks very much!

**Comment by johndharrison** [comment]
Please use `wdman::phantomjs(retcommand = TRUE)` to install phantomjs. You can then run using the `rsDriver` function in `RSelenium` or the `wdman::phantomjs` to drive phantomjs directly.
