### ISSUE TITLE
RSelenium 1.4.0 error on starting server on windows

### ISSUE THREAD

**Issue by fvalenduc** [ropensci/RSelenium#82]
When I start RSelenium on Windows, it gives the following error message:

> startServer(log=FALSE)
> Error in if (file.exists(file) == FALSE) if (!missing(asText) && asText ==  : 
>   argument is of length zero
> In addition: Warning message:
> running command '"wmic" path win32_process get Caption,Processid,Commandline /format:htable' had status 44210 

However, the server is started and can be used. Can you verify what is happening ?
An obvious workaround is this:
try(startServer(log=FALSE),silent=TRUE) so that scripts don't fail, but it is a bit annoying having to adapt all my codes.

Thanks for your help.

**Comment by johndharrison** [comment]
It is most likely an issue with your version of windows. See

http://stackoverflow.com/questions/38933424/rselenium-issue-with-startserver-on-windows/38934238#38934238

**Comment by fvalenduc** [comment]
Indeed, copying xsl files like suggested solves the problem. However, this is not doable without administrator rights like on my professional PC. So,  can you explain how you pass the correct arguments to the WMIC command ? Do I need to modify the code in the code of the startServer() function in util.r ?
Since it seems to be a bug in a lot of versions of windows, I believe this code is problematic.

**Comment by johndharrison** [comment]
- startServer is a utility function.

- The object of `RSelenium` is to provide bindings for the JSONwireprotocol. 

- You have the option to manually start your own server as detailed in the [basic vignette](http://rpubs.com/johndharrison/12843)

- You have the option to run a docker container as detailed in the [docker vignette](http://rpubs.com/johndharrison/RSelenium-Docker)

- You have the option to write your function which doesnt return functions to kill the server and return its process id:

```
myStartServer <- function (dir = NULL, args = NULL, javaargs = NULL, log = TRUE,  ...) 
{
  selDIR <-  ifelse(is.null(dir), file.path(find.package("RSelenium"), 
                                            "bin"), dir)
  selFILE <- file.path(selDIR, "selenium-server-standalone.jar")
  if (!file.exists(selFILE)) {
    possFiles <- list.files(selDIR, "selenium-server-standalone")
    if(length(possFiles) == 0){
      stop("No Selenium Server binary exists. Run checkForServer or start server manually.")
    }
    # pick most recent driver
    selFILE <- possFiles[order(gsub(".*-(.*).jar$", "\\1", possFiles), decreasing = TRUE)][1]
    selFILE <- file.path(selDIR, selFILE)
  }
  logFILE <- file.path(selDIR, "sellog.txt")
  selArgs <- c(paste("-jar", shQuote(selFILE)))
  if(log){
    write("", logFILE)
    selArgs <- c(selArgs, paste("-log", shQuote(logFILE)))
  }
  selArgs <- c(javaargs, selArgs, args)
  userArgs <- list(...)
  if (.Platform$OS.type == "unix") {
    initArgs <- list(command = "java", args = selArgs, wait = FALSE, stdout = FALSE, stderr = FALSE)
  }
  else {
    initArgs <- list(command = "java",args = selArgs, wait = FALSE, invisible = TRUE)
  }
  initArgs[names(userArgs)] <- userArgs 
do.call(system2, initArgs)
)
```

**Comment by fvalenduc** [comment]
Using a custom startServer or starting the server manually will also solves the problem, which requires to adapt all my codes. 
Since this is a known issue in Windows, is there no way to put the correct arguments to WMIC in the original startServer function so that the upgrade is transparent to windows users ?

**Comment by johndharrison** [comment]
I don't provide IT support for every OS every user may run.  The arguments presented to WMIC are correct. It is an issue with what I presume is Windows 7 as you haven't provided this information.  Giving the "correct" arguments would require knowing information about your systems locale. 

I will be deprecating `startServer` and `checkForServer` in line with other language clients who leave the starting of a Selenium Server to the end user in future versions of` RSelenium` so this won't be an issue.

**Comment by johndharrison** [comment]
@fvalenduc here is a patched version of startServer to try.  I download win 7 from 
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ as a virtual machine. wmic functions correctly on this vm however and I cannot replicate your issue. 

You can try the below patched version of startServer and if it works I will add it:

```
startServer <- function (dir = NULL, args = NULL, javaargs = NULL, log = TRUE,  ...) 
{
  .Deprecated(package = "RSelenium", msg = "startServer is deprecated.
Users in future can find the function in file.path(find.package(\"RSelenium\"), \"example/serverUtils\").
The sourcing/starting of a Selenium Server is a users responsiblity. 
Options include manually starting a server see vignette(\"RSelenium-basics\", package = \"RSelenium\")
and running a docker container see  vignette(\"RSelenium-docker\", package = \"RSelenium\")")
  selDIR <-  ifelse(is.null(dir), file.path(find.package("RSelenium"), 
                                            "bin"), dir)
  selFILE <- file.path(selDIR, "selenium-server-standalone.jar")
  if (!file.exists(selFILE)) {
    possFiles <- list.files(selDIR, "selenium-server-standalone")
    if(length(possFiles) == 0){
      stop("No Selenium Server binary exists. Run checkForServer or start server manually.")
    }
    # pick most recent driver
    selFILE <- possFiles[order(gsub(".*-(.*).jar$", "\\1", possFiles), decreasing = TRUE)][1]
    selFILE <- file.path(selDIR, selFILE)
  }
  logFILE <- file.path(selDIR, "sellog.txt")
  selArgs <- c(paste("-jar", shQuote(selFILE)))
  if(log){
    write("", logFILE)
    selArgs <- c(selArgs, paste("-log", shQuote(logFILE)))
  }
  selArgs <- c(javaargs, selArgs, args)
  userArgs <- list(...)
  if (.Platform$OS.type == "unix") {
    initArgs <- list(command = "java", args = selArgs, wait = FALSE, stdout = FALSE, stderr = FALSE)
  }
  else {
    initArgs <- list(command = "java",args = selArgs, wait = FALSE, invisible = TRUE)
  }
  initArgs[names(userArgs)] <- userArgs 
  do.call(system2, initArgs)
  if (.Platform$OS.type == "windows"){
    wmicOut <- tryCatch({
      system2("wmic",
              args = c("path win32_process get Caption,Processid,Commandline"
                       , "/format:htable")
              , stdout=TRUE, stderr=NULL)
    }, error = function(e)e)
    selPID <- if(inherits(wmicOut, "error")){
      wmicArgs <- paste0(c("path win32_process where \"commandline like '%",
                           selFILE, "%'\" get Processid"))
      wmicOut <- system2("wmic", 
              args = wmicArgs
              , stdout = TRUE)
      as.integer(gsub("\r", "", wmicOut[2]))
    }else{
      wmicOut <- readHTMLTable(htmlParse(wmicOut), header = TRUE, stringsAsFactors = FALSE)[[1]]
      wmicOut[["ProcessId"]] <- as.integer(wmicOut[["ProcessId"]])
      idx <- grepl(selFILE, wmicOut$CommandLine)
      if(!any(idx)) stop("Selenium binary error: Unable to start Selenium binary. Check java is installed.")
      wmicOut[idx,"ProcessId"]
    }
  }else{
    if(Sys.info()["sysname"] == "Darwin"){
      sPids <- system('ps -Ao"pid"', intern = TRUE)
      sArgs <- system('ps -Ao"args"', intern = TRUE)
    }else{
      sPids <- system('ps -Ao"%p"', intern = TRUE)
      sArgs <- system('ps -Ao"%a"', intern = TRUE)
    }
    idx <- grepl(selFILE, sArgs)
    if(!any(idx)) stop("Selenium binary error: Unable to start Selenium binary. Check java is installed.")
    selPID <- as.integer(sPids[idx])
  }
  
  list(
    stop = function(){
      tools::pskill(selPID)
    },
    getPID = function(){
      return(selPID)
    }
  )
}
```

**Comment by fvalenduc** [comment]
This is the core og the problem. The new code works correctly if wmic functions correctly. I am curious to know the percentage of computers where it is the case....
My professional and private PCs uses both windows 7 and either I have to add the locale to the wmic command or I have to copy the files in C:\Windows\System32\wbem.
So unfortunately, your new code doesn't change anything for me.

**Comment by fvalenduc** [comment]
This small change solves my problem:

startServer <- function (dir = NULL, args = NULL, javaargs = NULL, log = TRUE,  ...) 
{
  .Deprecated(package = "RSelenium", msg = "startServer is deprecated.
Users in future can find the function in file.path(find.package(\"RSelenium\"), \"example/serverUtils\").
The sourcing/starting of a Selenium Server is a users responsiblity. 
Options include manually starting a server see vignette(\"RSelenium-basics\", package = \"RSelenium\")
and running a docker container see  vignette(\"RSelenium-docker\", package = \"RSelenium\")")
  selDIR <-  ifelse(is.null(dir), file.path(find.package("RSelenium"), 
                                            "bin"), dir)
  selFILE <- file.path(selDIR, "selenium-server-standalone.jar")
  if (!file.exists(selFILE)) {
    possFiles <- list.files(selDIR, "selenium-server-standalone")
    if(length(possFiles) == 0){
      stop("No Selenium Server binary exists. Run checkForServer or start server manually.")
    }
    # pick most recent driver
    selFILE <- possFiles[order(gsub(".*-(.*).jar$", "\\1", possFiles), decreasing = TRUE)][1]
    selFILE <- file.path(selDIR, selFILE)
  }
  logFILE <- file.path(selDIR, "sellog.txt")
  selArgs <- c(paste("-jar", shQuote(selFILE)))
  if(log){
    write("", logFILE)
    selArgs <- c(selArgs, paste("-log", shQuote(logFILE)))
  }
  selArgs <- c(javaargs, selArgs, args)
  userArgs <- list(...)
  if (.Platform$OS.type == "unix") {
    initArgs <- list(command = "java", args = selArgs, wait = FALSE, stdout = FALSE, stderr = FALSE)
  }
  else {
    initArgs <- list(command = "java",args = selArgs, wait = FALSE, invisible = TRUE)
  }
  initArgs[names(userArgs)] <- userArgs 
  do.call(system2, initArgs)
  if (.Platform$OS.type == "windows"){
    wmicOut <- tryCatch({
      system2("wmic",
              args = c("path win32_process get Caption,Processid,Commandline"
                       , "/format:htable")
              , stdout=TRUE, stderr=NULL)
    },error=function(e) e, warning=function(w) w)
    selPID <- if(is(wmicOut,"warning")) {
      wmicArgs <- paste0(c("path win32_process where \"commandline like '%",
                           selFILE, "%'\" get Processid"))
      wmicOut <- system2("wmic", 
              args = wmicArgs
              , stdout = TRUE)
      as.integer(gsub("\r", "", wmicOut[2]))
    }else{
      wmicOut <- readHTMLTable(htmlParse(wmicOut), header = TRUE, stringsAsFactors = FALSE)[[1]]
      wmicOut[["ProcessId"]] <- as.integer(wmicOut[["ProcessId"]])
      idx <- grepl(selFILE, wmicOut$CommandLine)
      if(!any(idx)) stop("Selenium binary error: Unable to start Selenium binary. Check java is installed.")
      wmicOut[idx,"ProcessId"]
    }
  }else{
    if(Sys.info()["sysname"] == "Darwin"){
      sPids <- system('ps -Ao"pid"', intern = TRUE)
      sArgs <- system('ps -Ao"args"', intern = TRUE)
    }else{
      sPids <- system('ps -Ao"%p"', intern = TRUE)
      sArgs <- system('ps -Ao"%a"', intern = TRUE)
    }
    idx <- grepl(selFILE, sArgs)
    if(!any(idx)) stop("Selenium binary error: Unable to start Selenium binary. Check java is installed.")
    selPID <- as.integer(sPids[idx])
  }

  list(
    stop = function(){
      tools::pskill(selPID)
    },
    getPID = function(){
      return(selPID)
    }
  )
}

However selServer$stop() doesn't stop the server.

**Comment by johndharrison** [comment]
@fvalenduc it is very difficult to debug an error I don't have access to. The new patch above I asked for the following:

```
selServ <- startServer()
selServer$getPID()
selServer$stop()
```
If the code doesn't work what output is given? Is a process id returned? The original error was with Win 7 using XSL templates to format return from wmic.  In the patch this error was caught an alternative method tried. 

Does the following commandline work for you?

> wmic path win32_process get Caption,Processid,Commandline

**Comment by fvalenduc** [comment]
I understand that is difficult to debug if you don't see the problem. It seems that the condition to try the alternative method was not correct. In my proposed version, I have changed it and it works.

**Comment by johndharrison** [comment]
Does the proposed fix with a warning handle work? Is a PID returned. Does selServ$stop() kill the selenium Server?

**Comment by fvalenduc** [comment]
It returns a PID. However, selServ$stop() doesn't kill the server, which might me another problem.

**Comment by a1zhan** [comment]
HI I have a different issue with RSElenium when I tried opening firefox browser.

FIrst of all I had a warning message when i  run startServer()
"Warning message:
startServer is deprecated.
Users in future can find the function in file.path(find.package("RSelenium"), "example/serverUtils").
The sourcing/starting of a Selenium Server is a users responsiblity. 
Options include manually starting a server see vignette("RSelenium-basics", package = "RSelenium")
and running a docker container see  vignette("RSelenium-docker", package = "RSelenium") "

I am not sure if this affects the performance?

But the error occurs when I try to open firefox:
> remDr <- remoteDriver(browserName="firefox") 
> remDr$open()

Selenium message: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1474578384000,"updateDate":1474578384000,"applyBackgroundUpdates":1,"skinnable":true,"size":21905,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.1","maxVersion":"49.0.1"}],"targetPlatforms":[],"seen":true}

Error: 	 Summary: UnknownError
 	 Detail: An unknown server-side error occurred while processing the command.
 	 class: org.openqa.selenium.firefox.NotConnectedException
	 Further Details: run errorDetails method

... and with phantomjs, it's a different error:
> remDr <- remoteDriver(browserName="phantomjs") ;
> remDr$open()

Selenium message: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html 
Error: 	 Summary: UnknownError
 	 Detail: An unknown server-side error occurred while processing the command.
 	 class: java.lang.IllegalStateException
	 Further Details: run errorDetails method

Could you help me with this issue?

Many thanks
