### ISSUE TITLE
RSelenium on shiny server

### ISSUE THREAD

**Issue by Theshan** [ropensci/RSelenium#83]
Rselenium code on shiny server doesn't run...

**Comment by johndharrison** [comment]
@Theshan in what way does the code not run?

**Comment by Theshan** [comment]
Sorry for the late reply @johndharrison 

I ran a test app in shinyapps.io where it uses the package RSelenium package to retrieve some site info.
The log showed errors at the RSelenium::startServer() function

This is a while ago let me know if you need the exact code.

Thanks!

**Comment by johndharrison** [comment]
@Theshan I doubt you will be able to run a selenium server on the shinyapps.io backend.

**Comment by Theshan** [comment]
@johndharrison Check out this repo. It is there to add dependencies for shinyapps. 

https://github.com/rstudio/shinyapps-package-dependencies/blob/master/CONTRIBUTING.md
