### ISSUE TITLE
Testing Shiny apps on travis

### ISSUE THREAD

**Issue by MarkEdmondson1234** [ropensci/RSelenium#86]
Hello, thanks for this handy package for testing Shiny apps.  I can do it locally, but I wondered if there is a guide somewhere on checking a Shiny app from Travis?  I'd like to check an RStudio gadget and some Shiny authentication functionality.

**Comment by johndharrison** [comment]
Hi Mark. 

Yes you can check a shiny package on Travis. If your project is open source you can use SauceLabs. They provide a free account for open source projects. If your shiny app is hosted locally (local to the machine doing the testing) you would need to use sauce-connect additionally. See
https://docs.travis-ci.com/user/gui-and-headless-browsers/

Another option is to use Docker containers to run a selenium server on Docker with a headless browser. See 
https://docs.travis-ci.com/user/docker/
You can use one of the Docker images at 
https://hub.docker.com/r/selenium/

**Comment by MarkEdmondson1234** [comment]
Great, thanks!  Will check out the links :)

**Comment by MarkEdmondson1234** [comment]
Sorry, one more follow up question - an aim for the testing is for code coverage to work, so it executes the code in the package (https://codecov.io/gh/MarkEdmondson1234/googleAuthR ) - do the above options run the local code so covr() will catch it running?  I have a demo app running publically on shinyapps.io so could use that if I didn't need the local code to run.

**Comment by johndharrison** [comment]
If you have the app hosted it would make it easier for you as you wouldnt need to run a local server on Travis. All you would need to do is have a selenium server running on travis. For example add something like:

sudo: required

language: R

services:
  - docker

before_install:selenium/standalone-firefox:2.53.0
- docker run -d -p 127.0.0.1:4444:4444 selenium/standalone-firefox:2.53.0

to your YAML. Then in your tests you can assume a headless firefox browser is available at 127.0.0.1:4444 to run your shiny tests on. 

The shiny tests are included in the package tests I am guessing so codecov should cover them and the docker Selenium, server will enable you to run them.

**Comment by MarkEdmondson1234** [comment]
Great, thanks for the example, will try it out. :)

**Comment by johndharrison** [comment]
Hi Mark,

seleniumPipes https://github.com/johndharrison/seleniumPipes has an example of TRAVIS and Selenium. The seleniumPipes tests require a selenium server and uses Docker in Travis.

See 

https://github.com/johndharrison/seleniumPipes/blob/master/.travis.yml

and 

https://github.com/johndharrison/seleniumPipes/blob/master/tests/testthat/test_api_example_tests.R

**Comment by MarkEdmondson1234** [comment]
Thanks John, will work from those as a basis
