### ISSUE TITLE
Has PhantomJS disappeared forever?

### ISSUE THREAD

**Issue by masalmon** [ropensci/RSelenium#87]
The website of PhantomJS and its Github repository seem to have disappeared (I used the links fromhttp://rpubs.com/johndharrison/RSelenium-headless ). Does PhantomJS no longer exist? Thanks in advance.

**Comment by johndharrison** [comment]
Maybe a temporary hiccup. https://twitter.com/AriyaHidayat/status/776651944433639424 and 
https://groups.google.com/forum/#!topic/phantomjs/0e_MZMoNTdU might bring some updates

**Comment by masalmon** [comment]
Many thanks, I'll follow the updates there and keep my fingers crossed.

**Comment by masalmon** [comment]
It's back now sorry for the false alert :smile_cat:
