### ISSUE TITLE
R session hangs if executeScript() in loop

### ISSUE THREAD

**Issue by huashan** [ropensci/RSelenium#95]
Hi, I'd like to drive RSelenium to do some loop while scraping. However, I found this simple script will hang R session for dead.  Is this by design or bug? I am using Windows 7 64bit, RSelenium 1.4.5.

```
remDr <- remoteDriver(remoteServerAddr = "localhost", port = 4444, browserName = "chrome")  
remDr$open()
for (i in 1:10) remDr$executeScript('return "1";')
```

**Comment by johndharrison** [comment]
What version of chromedriver are you using? https://sites.google.com/a/chromium.org/chromedriver/downloads

```
> remDr$sessionInfo$chrome
$chromedriverVersion
[1] "2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf)"
```

**Comment by johndharrison** [comment]
This is most likely the same issue as #106 thou i couldn't replicate with chrome locally.
