### ISSUE TITLE
remDr$open() returning error on Ubuntu 14 LTS

### ISSUE THREAD

**Issue by ganeshnikumbh** [ropensci/RSelenium#97]
code:
startServer()
remDr <- remoteDriver()
remDr$open()

This works on my windows machine. But not in Ubuntu. I immediately get  below error.

Below are the details. Please let me know a solution

error

remDr$open()
[1] "Connecting to remote server"
Undefined error in RCurl call.
Error in queryRD(paste0(serverURL, "/session/", sessionInfo$id)) : 

Java Version:
cts1@pc236007:/usr/bin$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

selenium server version downloaded and placed in Rselenium/bin folder
selenium-server-standalone-2.53.1.jar

devtools::session_info()
Session info -----------------------------------------------------------------------------------------
 setting  value  
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, linux-gnu  
 ui       RStudio (0.99.903)  
 language en_IN:en  
 collate  en_IN.UTF-8  
 tz       Asia/Calcutta  
 date     2016-10-20                  

Packages ---------------------------------------------------------------------------------------------
 package    \* version  date       source  
 bitops     \* 1.0-6    2013-08-17 CRAN (R 3.2.2)  
 caTools      1.17.1   2014-09-10 CRAN (R 3.2.2)  
 codetools    0.2-14   2015-07-15 CRAN (R 3.2.2)  
 devtools   \* 1.9.1    2015-09-11 CRAN (R 3.2.2)  
 digest       0.6.8    2014-12-31 CRAN (R 3.2.2)  
 gdata      \* 2.17.0   2016-08-12 R-Forge (R 3.2.2)  
 gtools       3.5.0    2015-05-29 CRAN (R 3.2.2)  
 httr         1.0.0    2015-06-25 CRAN (R 3.2.2)  
 magrittr     1.5      2014-11-22 CRAN (R 3.2.2)  
 memoise      0.2.1    2014-04-22 CRAN (R 3.2.2)  
 R6           2.1.1    2015-08-19 CRAN (R 3.2.2)  
 Rcpp         0.12.1   2015-09-10 CRAN (R 3.2.2)  
 RCurl      \* 1.95-4.7 2015-06-30 CRAN (R 3.2.2)  
 rjson        0.2.15   2014-11-03 CRAN (R 3.2.2)  
 rsconnect    0.4.1.4  2015-10-14 Github (rstudio/rsconnect@fcac892)
 RSelenium  \* 1.4.5    2016-10-02 CRAN (R 3.2.2)  
 rstudioapi   0.3.1    2015-04-07 CRAN (R 3.2.2)  
 rvest      \* 0.3.2    2016-06-17 CRAN (R 3.2.2)  
 stringi      0.5-5    2015-06-29 CRAN (R 3.2.2)  
 stringr      1.0.0    2015-04-30 CRAN (R 3.2.2)  
 XML        \* 3.98-1.4 2016-03-01 CRAN (R 3.2.2)  
 xml2       \* 0.1.2    2015-09-01 CRAN (R 3.2.2)

**Comment by johndharrison** [comment]
Hi @ganeshnikumbh startServer is deprecated please look at running RSelenium with Docker http://rpubs.com/johndharrison/RSelenium-Docker or look at starting the selenium jar manually.

**Comment by ganeshnikumbh** [comment]
Hi John, I tried starting the server manually. still getting the same error. Can you please help?
